<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>PalORM.AotModels.First</RootNamespace>
    <AssemblyName>PalORM.AotModels.First</AssemblyName>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\PalORM.Core\PalORM.Core.csproj" />
    <ProjectReference Include="..\..\src\PalORM.SourceGen\PalORM.SourceGen.csproj"
                      OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
  </ItemGroup>
</Project>
