<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>PalORM.PackageConsumer.Aot</RootNamespace>
    <AssemblyName>PalORM.PackageConsumer.Aot</AssemblyName>
    <IsPackable>false</IsPackable>
    <ManagePackageVersionsCentrally>false</ManagePackageVersionsCentrally>
    <PublishAot>true</PublishAot>
    <PublishTrimmed>true</PublishTrimmed>
    <JsonSerializerIsReflectionEnabledByDefault>false</JsonSerializerIsReflectionEnabledByDefault>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="PalORM.Core" Version="5.0.0" />
    <PackageReference Include="PalORM.Sqlite" Version="5.0.0" />
    <PackageReference Include="PalORM.SourceGen" Version="5.0.0" PrivateAssets="all" />
  </ItemGroup>
</Project>
