namespace PalORM.SourceGen.Tests;

/// <summary>
/// 三方言对称性清单测试（ITM-303/304/315/326 类缺陷的机械防线）。
/// 原则：对同一实体模型生成三方言全部 SQL 产物，将「预期方言差异表」中登记的差异
/// 归一化为占位符后逐项 diff——归一化后仍不一致 = 出现了未登记的方言差异 = 测试失败。
/// 新增合法方言差异时，必须先在下方差异表登记（占位符 + 注释说明依据），再更新断言。
/// </summary>
internal sealed class DialectSymmetryTests
{
    // ───────────────────────────── 预期方言差异表 ─────────────────────────────
    // │ 差异点            │ SQLite                    │ PostgreSql                │ MySql
    // │ 标识符引用符      │ "x"                       │ "x"                       │ `x`
    // │ 自增主键子句      │ PRIMARY KEY AUTOINCREMENT │ GENERATED BY DEFAULT AS   │ AUTO_INCREMENT
    // │                   │                           │ IDENTITY PRIMARY KEY      │ PRIMARY KEY
    // │ 自增主键列类型    │ INTEGER（rowid 要求）     │ BIGINT                    │ BIGINT
    // │ RETURNING 子句    │ 有                        │ 有                        │ 无（空串哨兵）
    // │ CREATE INDEX 幂等 │ IF NOT EXISTS             │ IF NOT EXISTS             │ 无（运行时 1061 兜底）
    // │ 被索引 string 列  │ TEXT                      │ TEXT                      │ VARCHAR(255)（1170）
    // │ double 列型       │ DOUBLE                    │ DOUBLE PRECISION          │ DOUBLE
    // │ DateTime 列型     │ TIMESTAMP                 │ TIMESTAMP                 │ DATETIME(6)
    // │ DateTimeOffset    │ TEXT                      │ TIMESTAMPTZ               │ DATETIME(6)
    // │ Guid 列型         │ TEXT                      │ UUID                      │ CHAR(36)
    // │ TimeOnly 列型     │ TIME                      │ TIME                      │ TIME(6)
    // │ 参数上限          │ 999                       │ 无硬限（COPY 独立路径）   │ 65535
    // ──────────────────────────────────────────────────────────────────────────

    private static readonly SqlGenerationDialect[] _dialects =
        [SqlGenerationDialect.Sqlite, SqlGenerationDialect.PostgreSql, SqlGenerationDialect.MySql];

    /// <summary>登记差异归一化：把上表中每个方言特有 token 替换为占位符。</summary>
    private static string Normalize(string sql, SqlGenerationDialect dialect)
    {
        // 引用符 → 去引用（测试实体标识符不含引用字符，直接删除）
        sql = dialect == SqlGenerationDialect.MySql
            ? sql.Replace("`", "", StringComparison.Ordinal)
            : sql.Replace("\"", "", StringComparison.Ordinal);

        // 自增主键子句
        sql = sql
            .Replace(" INTEGER PRIMARY KEY AUTOINCREMENT", " «PK-AUTO»", StringComparison.Ordinal)
            .Replace(" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY", " «PK-AUTO»", StringComparison.Ordinal)
            .Replace(" BIGINT AUTO_INCREMENT PRIMARY KEY", " «PK-AUTO»", StringComparison.Ordinal);

        // CREATE INDEX 幂等前缀
        sql = sql.Replace("INDEX IF NOT EXISTS ", "INDEX «IDEMPOTENT»", StringComparison.Ordinal);
        if (dialect == SqlGenerationDialect.MySql)
            sql = sql.Replace("INDEX ", "INDEX «IDEMPOTENT»", StringComparison.Ordinal);

        // 列类型（顺序敏感：长 token 先替换）
        sql = sql
            .Replace(" DOUBLE PRECISION", " «DOUBLE»", StringComparison.Ordinal)
            .Replace(" DOUBLE", " «DOUBLE»", StringComparison.Ordinal)
            .Replace(" DATETIME(6)", " «DIALECT-TEMPORAL»", StringComparison.Ordinal)
            .Replace(" TIMESTAMPTZ", " «DTO»", StringComparison.Ordinal)
            .Replace(" TIMESTAMP", " «DIALECT-TEMPORAL»", StringComparison.Ordinal)
            .Replace(" TIME(6)", " «TIME»", StringComparison.Ordinal)
            .Replace(" TIME", " «TIME»", StringComparison.Ordinal)
            .Replace(" UUID", " «GUID»", StringComparison.Ordinal)
            .Replace(" CHAR(36)", " «GUID»", StringComparison.Ordinal)
            .Replace(" VARCHAR(255)", " «INDEXED-STRING»", StringComparison.Ordinal);
        // 列名限定的方言落型：SQLite 的 DTO/Guid 落 TEXT、MySQL 的 DTO 落 DATETIME(6)，
        // 与其他类型 token 重叠，按本测试实体列名归一
        sql = sql
            .Replace("dto_value TEXT", "dto_value «DTO»", StringComparison.Ordinal)
            .Replace("dto_value «DIALECT-TEMPORAL»", "dto_value «DTO»", StringComparison.Ordinal)
            .Replace("guid_value TEXT", "guid_value «GUID»", StringComparison.Ordinal)
            .Replace("sku TEXT", "sku «INDEXED-STRING»", StringComparison.Ordinal);
        return sql;
    }

    private static readonly TableModel _model = new(
        Namespace: "Symmetry",
        ClassName: "SymmetryEntity",
        EntityTypeName: "global::Symmetry.SymmetryEntity",
        GeneratedTypeSuffix: "Symmetry_SymmetryEntity",
        TableName: "symmetry_items",
        IsView: false,
        IsSoftDelete: true,
        IsTenantAware: true,
        Columns: new EquatableArray<ColumnModel>(new ColumnModel[]
        {
            Column("Id", "id", "long", "BIGINT", isPrimaryKey: true, isAutoIncrement: true),
            Column("Sku", "sku", "string", "TEXT", isRequired: true),
            Column("Name", "name", "string", "TEXT"),
            Column("Amount", "amount", "decimal", "DECIMAL"),
            Column("Ratio", "ratio", "double", "DOUBLE"),
            Column("CreatedAt", "created_at", "global::System.DateTime", "TIMESTAMP"),
            Column("DtoValue", "dto_value", "global::System.DateTimeOffset", "TIMESTAMPTZ"),
            Column("GuidValue", "guid_value", "global::System.Guid", "UUID"),
            Column("TimeValue", "time_value", "global::System.TimeOnly", "TIME"),
            Column("Version", "version", "long", "BIGINT", isConcurrencyToken: true),
            Column("Note", "note", "string", "TEXT", isNullable: true),
        }),
        Indexes: new EquatableArray<IndexModel>(new IndexModel[]
        {
            new("ux_symmetry_sku", new EquatableArray<string>(new[] { "sku" }), Unique: true),
        }),
        ForeignKeys: new EquatableArray<ForeignKeyModel>(System.Array.Empty<ForeignKeyModel>()),
        Schema: null,
        Database: null);

    private static ColumnModel Column(
        string property, string column, string clrType, string dbType,
        bool isPrimaryKey = false, bool isAutoIncrement = false, bool isNullable = false,
        bool isRequired = false, bool isConcurrencyToken = false)
        => new(
            property, column, clrType, clrType, dbType, isPrimaryKey, isAutoIncrement,
            isNullable, isRequired, null, null, null, null,
            IgnoreOnInsert: false, IsConcurrencyToken: isConcurrencyToken, IsTimestamp: false,
            ComputedExpression: null, IsOwnedJson: false, OwnedJsonContextTypeName: null,
            ConverterTypeName: null);

    [Test]
    public async Task InsertSql_IsSymmetricAcrossDialects()
        => await AssertSymmetric(dialect => CommandFactoryEmitter.BuildInsertSql(_model, dialect));

    [Test]
    public async Task UpdateSql_IsSymmetricAcrossDialects()
        => await AssertSymmetric(dialect => CommandFactoryEmitter.BuildUpdateSql(_model, dialect));

    [Test]
    public async Task DeleteSql_IsSymmetricAcrossDialects()
        => await AssertSymmetric(dialect => CommandFactoryEmitter.BuildDeleteSql(_model, dialect));

    [Test]
    public async Task InsertReturningSql_MySqlEmpty_OthersSymmetric()
    {
        // MySQL 无 RETURNING（登记差异）：空串哨兵，消费端由 SupportsReturningClause 守卫
        string mysql = CommandFactoryEmitter.BuildInsertReturningSql(_model, SqlGenerationDialect.MySql);
        await Assert.That(mysql).IsEmpty();

        string sqlite = Normalize(
            CommandFactoryEmitter.BuildInsertReturningSql(_model, SqlGenerationDialect.Sqlite),
            SqlGenerationDialect.Sqlite);
        string postgres = Normalize(
            CommandFactoryEmitter.BuildInsertReturningSql(_model, SqlGenerationDialect.PostgreSql),
            SqlGenerationDialect.PostgreSql);
        await Assert.That(sqlite).IsEqualTo(postgres);
    }

    [Test]
    public async Task CreateTableSql_IsSymmetricAcrossDialects()
        => await AssertSymmetric(dialect => MigrationEmitter.BuildCreateTable(_model, dialect));

    [Test]
    public async Task CreateIndexSql_IsSymmetricAcrossDialects()
        => await AssertSymmetric(dialect =>
            MigrationEmitter.BuildCreateIndex(_model, _model.Indexes.AsSpan()[0], dialect));

    [Test]
    public async Task AllDialectSqls_QuoteIdentifiers()
    {
        // ITM-416：归一化把引用符整串删除——某方言漏引用标识符时归一化产物仍一致，
        // 对"引用符存在性"失明。此断言独立验证每个方言产物确实引用了标识符。
        // Upsert SQL 由运行时构建（DataSession.BuildMySqlUpsertSql/SaveCoreAsync 经
        // QuoteIdentifier），不在 Emitter 对称面内。
        var builds = new (string Name, Func<SqlGenerationDialect, string> Build)[]
        {
            ("Insert", d => CommandFactoryEmitter.BuildInsertSql(_model, d)),
            ("Update", d => CommandFactoryEmitter.BuildUpdateSql(_model, d)),
            ("Delete", d => CommandFactoryEmitter.BuildDeleteSql(_model, d)),
            ("CreateTable", d => MigrationEmitter.BuildCreateTable(_model, d)),
            ("CreateIndex", d => MigrationEmitter.BuildCreateIndex(_model, _model.Indexes.AsSpan()[0], d)),
        };
        var violations = new List<string>();
        foreach ((string name, Func<SqlGenerationDialect, string> build) in builds)
        {
            foreach (SqlGenerationDialect dialect in _dialects)
            {
                string sql = build(dialect);
                char quote = dialect == SqlGenerationDialect.MySql ? '`' : '"';
                // 表名必须以引用形式出现（symmetry_items 被引用符包裹）
                if (!sql.Contains($"{quote}symmetry_items{quote}", StringComparison.Ordinal))
                    violations.Add($"{name}/{dialect}: 表名未被 {quote} 引用\n  SQL: {sql}");
            }
        }
        await Assert.That(string.Join("\n", violations)).IsEmpty();
    }

    /// <summary>归一化后三方言产物必须逐字符一致；不一致 = 未登记的方言差异。</summary>
    private static async Task AssertSymmetric(Func<SqlGenerationDialect, string> build)
    {
        var normalized = _dialects
            .Select(dialect => (Dialect: dialect, Sql: Normalize(build(dialect), dialect)))
            .ToArray();

        foreach (var (dialect, sql) in normalized.Skip(1))
        {
            await Assert.That(sql)
                .IsEqualTo(normalized[0].Sql)
                .Because($"{dialect} 与 {normalized[0].Dialect} 归一化后仍有差异——" +
                    "若为有意差异，先在 DialectSymmetryTests 顶部差异表登记再更新 Normalize");
        }
    }
}
