// probe-pgvector.cs（向量门结论 B 分支的核对清单自动化，docs/向量搜索Raw配方.md §五）
// 在具备 pgvector 扩展的 PG 库上验证 Raw 配方的六项形态；无扩展时输出指引并以
// 退出码 2 结束（环境门控——明确报告未验证原因，不静默跳过、不以绿呈现）。
//
// 用法: PALORM_PG_CONNECTION="Host=...;Database=...;Username=...;Password=..."
//       dotnet run --file scripts/probe-pgvector.cs
// 退出码: 0=六项全过 · 1=有失败（配方形态有问题）· 2=pgvector 不可用（环境门控）
//
// 本脚本为一次性探针工具（真库形态验证），不属于产品 API 面；表名带 probe 前缀
// 且 finally 自清理，可在共享库上安全运行。
#:property ManagePackageVersionsCentrally=false
#:package Npgsql@10.0.3

using System.Text;
using Npgsql;

Console.OutputEncoding = new UTF8Encoding(false);
string? connString = Environment.GetEnvironmentVariable("PALORM_PG_CONNECTION");
if (string.IsNullOrWhiteSpace(connString))
{
    Console.Error.WriteLine("FATAL: 未设置 PALORM_PG_CONNECTION（探针需要真库连接串）");
    return 2;
}

const string TableName = "palorm_pgvector_probe";
await using var conn = new NpgsqlConnection(connString);
try
{
    await conn.OpenAsync(new CancellationTokenSource(TimeSpan.FromSeconds(15)).Token);
}
catch (Exception ex)
{
    Console.Error.WriteLine($"GATE  连接失败（环境门控）: {ex.Message}");
    return 2;
}

// pgvector 可用性门控
bool hasVector;
await using (var cmd = new NpgsqlCommand(
    "SELECT COUNT(*) FROM pg_extension WHERE extname = 'vector'", conn))
{
    hasVector = Convert.ToInt64(await cmd.ExecuteScalarAsync()) > 0;
}
if (!hasVector)
{
    Console.Error.WriteLine("GATE  pgvector 扩展未安装（CREATE EXTENSION vector 前置：服务器装扩展包）——配方六项无法验证");
    return 2;
}

int pass = 0, fail = 0;
async Task CheckAsync(string name, Func<Task> probe)
{
    try
    {
        await probe();
        pass++;
        Console.WriteLine($"PASS  {name}");
    }
    catch (Exception ex)
    {
        fail++;
        Console.WriteLine($"FAIL  {name}: {ex.Message}");
    }
}

try
{
    // ① 建表 + Raw 补列（ADD COLUMN IF NOT EXISTS 幂等形态）
    await CheckAsync("①补列 DDL（ADD COLUMN IF NOT EXISTS vector(3)）", async () =>
    {
        await using var ddl = new NpgsqlCommand($"""
            CREATE TABLE IF NOT EXISTS {TableName} ("Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "content" TEXT NOT NULL);
            ALTER TABLE {TableName} ADD COLUMN IF NOT EXISTS "embedding" vector(3);
            """, conn);
        await ddl.ExecuteNonQueryAsync();
        await using var check = new NpgsqlCommand(
            $"SELECT data_type FROM information_schema.columns WHERE table_name = '{TableName}' AND column_name = 'embedding'", conn);
        string? type = await check.ExecuteScalarAsync() as string;
        if (type != "VECTOR") throw new InvalidOperationException($"列型 {type} ≠ VECTOR");
    });

    // ② ::vector 显式 cast 写入 + ::text 回读核值（铁证 1/2 的形态直证）
    await CheckAsync("②::vector 参数化写入 + ::text 回读", async () =>
    {
        await using var cmd = new NpgsqlCommand(
            $"INSERT INTO {TableName} (\"content\", \"embedding\") VALUES (@c, @v::vector)", conn);
        cmd.Parameters.AddWithValue("c", "probe");
        cmd.Parameters.AddWithValue("v", "[0.1,0.2,0.3]");
        await cmd.ExecuteNonQueryAsync();

        await using var read = new NpgsqlCommand(
            $"SELECT \"embedding\"::text FROM {TableName} WHERE \"content\" = 'probe' LIMIT 1", conn);
        string? back = await read.ExecuteScalarAsync() as string;
        if (back is null || !back.Replace(" ", "").Contains("0.1")) throw new InvalidOperationException($"回读异常: {back}");
    });

    // ③ 裸 text 参数直写（应失败——铁证 1 的反向验证：explicit-only cast）
    await CheckAsync("③裸 text 直写必败（负向形态直证）", async () =>
    {
        await using var cmd = new NpgsqlCommand(
            $"INSERT INTO {TableName} (\"content\", \"embedding\") VALUES (@c, @v)", conn);
        cmd.Parameters.AddWithValue("c", "negative");
        cmd.Parameters.AddWithValue("v", "[0.4,0.5,0.6]");
        try
        {
            await cmd.ExecuteNonQueryAsync();
            throw new InvalidOperationException("裸 text 直写竟然成功——与 PG CREATE CAST 文档的 explicit-only 结论冲突，配方前提需重审");
        }
        catch (PostgresException ex) when (ex.SqlState is "42883" or "42804" or "22P02")
        {
            // 预期失败形态（类型不存在/无法转换/非法字面量）
        }
    });

    // ④ 维度错配响亮失败
    await CheckAsync("④维度错配响亮拒绝", async () =>
    {
        await using var cmd = new NpgsqlCommand(
            $"INSERT INTO {TableName} (\"content\", \"embedding\") VALUES (@c, @v::vector)", conn);
        cmd.Parameters.AddWithValue("c", "wrongdim");
        cmd.Parameters.AddWithValue("v", "[0.1,0.2]");
        try
        {
            await cmd.ExecuteNonQueryAsync();
            throw new InvalidOperationException("维度错配竟然成功——列定义 vector(3) 未生效");
        }
        catch (PostgresException)
        {
            // 预期失败
        }
    });

    // ⑤ HNSW 索引 + 运算符类匹配（EXPLAIN 走索引）
    await CheckAsync("⑤HNSW 索引与运算符类匹配（EXPLAIN 走索引）", async () =>
    {
        await using var idx = new NpgsqlCommand(
            $"CREATE INDEX IF NOT EXISTS ix_{TableName}_emb ON {TableName} USING hnsw (\"embedding\" vector_l2_ops)", conn);
        await idx.ExecuteNonQueryAsync();
        await using var explain = new NpgsqlCommand(
            $"EXPLAIN SELECT \"Id\" FROM {TableName} ORDER BY \"embedding\" <-> '[0.1,0.2,0.3]'::vector LIMIT 5", conn);
        string plan = (string?)await explain.ExecuteScalarAsync() ?? "";
        if (!plan.Contains("Index Scan", StringComparison.OrdinalIgnoreCase) && !plan.Contains("hnsw", StringComparison.OrdinalIgnoreCase))
            throw new InvalidOperationException($"计划未走索引: {plan.Trim()}");
    });

    // ⑥ 幂等复跑（补列/索引 DDL 二次执行无错）
    await CheckAsync("⑥幂等复跑（DDL 二次执行）", async () =>
    {
        await using var ddl = new NpgsqlCommand(
            $"ALTER TABLE {TableName} ADD COLUMN IF NOT EXISTS \"embedding\" vector(3);" +
            $"CREATE INDEX IF NOT EXISTS ix_{TableName}_emb ON {TableName} USING hnsw (\"embedding\" vector_l2_ops)", conn);
        await ddl.ExecuteNonQueryAsync();
    });
}
finally
{
    await using var cleanup = new NpgsqlCommand(
        $"DROP TABLE IF EXISTS {TableName}", conn);
    try { await cleanup.ExecuteNonQueryAsync(); } catch { /* 清理失败不影响结论 */ }
}

Console.WriteLine($"\n核对清单: {pass} 过 / {fail} 败（docs/向量搜索Raw配方.md §五）");
return fail == 0 ? 0 : 1;
