<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>PalORM.MySql</RootNamespace>
    <AssemblyName>PalORM.MySql</AssemblyName>
    <Description>PalORM MySQL Provider — MySqlConnector 适配</Description>
    <PackageTags>ORM;MySQL;MySqlConnector;AOT;micro-ORM</PackageTags>
    <Version>4.6.0</Version>
    <NoWarn>$(NoWarn);CA2100;CA2007;NU5104</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\PalORM.Core\PalORM.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MySqlConnector" />
  </ItemGroup>
</Project>
