<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>PalORM.Sqlite</RootNamespace>
    <AssemblyName>PalORM.Sqlite</AssemblyName>
    <Description>PalORM SQLite Provider — Microsoft.Data.Sqlite.Core + SQLite3MC 适配</Description>
    <PackageTags>ORM;SQLite;AOT;micro-ORM</PackageTags>
    <!-- Version 由 Directory.Build.props 集中管理 -->
    <NoWarn>$(NoWarn);CA2100;CA2007;NU5104</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\PalORM.Core\PalORM.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite.Core" />
    <PackageReference Include="SQLite3MC.PCLRaw.bundle" />
    <PackageReference Include="Microsoft.SourceLink.GitHub" PrivateAssets="all" />
  </ItemGroup>
</Project>
