// v5.1 Auto Tagging Interceptor：扫描 6 个终态方法调用，生成 [InterceptsLocation] 拦截方法。
// 拦截方法体注入 builder.Tag(\"relativePath:line member\")，自动给 SQL 加源码定位注释。
// ITM-775(r21)：删除头部残留的 // <auto-generated/> 与文件级 CS1591 抑制——本文件是
// Emitter 源码（全 SourceGen 唯一带生成物头部模板）；auto-generated 标记会让分析器把
// 本文件按生成代码跳过诊断，CS1591 对 internal 类型无效且属禁止清单 #9 的削弱型抑制。
#nullable enable

using System.Collections.Immutable;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Operations;

namespace PalORM.SourceGen;

/// <summary>
/// Auto Tagging Interceptor 生成器：扫描 6 个终态方法调用，生成 [InterceptsLocation] 拦截方法。
/// </summary>
/// <remarks>
/// <b>工作原理</b>：源生成器在编译期检测 <c>QueryBuilderExtensions</c> 的 6 个终态方法调用，
/// 为每个调用点生成一个拦截方法。拦截方法体注入 <c>builder.Tag(...)</c> 后调用原方法，
/// 实现"用户零代码改动，SQL 自动带源码定位注释"。<br/>
/// <b>opt-in 开关</b>：消费侧 csproj 设置 <c>&lt;PalORMAutoTagging&gt;true&lt;/PalORMAutoTagging&gt;</c> 启用。
/// </remarks>
internal static class AutoTaggingEmitter
{
    /// <summary>
    /// 6 个终态方法定义：方法名 → 返回类型（用于生成签名匹配的拦截方法）。
    /// 签名差异仅在返回类型；参数列表统一为 (this QueryBuilder&lt;T&gt; builder, CancellationToken ct = default)。
    /// </summary>
    private static readonly ImmutableArray<TerminalMethod> s_terminals = new[]
    {
        new TerminalMethod("ToListAsync", "global::System.Threading.Tasks.ValueTask<global::System.Collections.Generic.List<T>>"),
        new TerminalMethod("FirstAsync", "global::System.Threading.Tasks.ValueTask<T>"),
        new TerminalMethod("FirstOrDefaultAsync", "global::System.Threading.Tasks.ValueTask<T?>"),
        new TerminalMethod("SingleAsync", "global::System.Threading.Tasks.ValueTask<T>"),
        new TerminalMethod("SingleOrDefaultAsync", "global::System.Threading.Tasks.ValueTask<T?>"),
        new TerminalMethod("ExecuteNonQueryAsync", "global::System.Threading.Tasks.ValueTask<int>"),
    }.ToImmutableArray();

    /// <summary>谓词：节点是 6 个终态方法之一的 InvocationExpression。</summary>
    public static bool IsTerminalCall(SyntaxNode node)
    {
        if (node is not InvocationExpressionSyntax invocation
            || invocation.Expression is not MemberAccessExpressionSyntax member)
            return false;
        string name = member.Name.Identifier.Text;
        foreach (var terminal in s_terminals)
        {
            if (name == terminal.Name) return true;
        }
        return false;
    }

    /// <summary>转换：提取调用点的 InterceptableLocation + 路径/行号/方法名。</summary>
    public static InterceptionTarget? ExtractTarget(GeneratorSyntaxContext ctx, CancellationToken ct)
    {
        var invocation = (InvocationExpressionSyntax)ctx.Node;
        if (ctx.SemanticModel.GetOperation(invocation, ct) is not IInvocationOperation op)
            return null;
        // 过滤：必须是 PalORM.QueryBuilderExtensions 的方法（排除其他同名方法）。
        // ITM-631：裸类名比对可被用户自定义同名静态类穿透——命名空间全限定精确匹配。
        if (op.TargetMethod.ContainingType is not { Name: "QueryBuilderExtensions" } containingType
            || containingType.ContainingNamespace?.ToDisplayString() != "PalORM")
            return null;

        // GetInterceptableLocation 扩展方法（CSharpExtensions 提供）
        InterceptableLocation? location = ctx.SemanticModel.GetInterceptableLocation(invocation, ct);
        if (location is null) return null;

        // 提取调用点位置信息（用于 Tag 注释）
        Location loc = invocation.GetLocation();
        FileLinePositionSpan span = loc.GetLineSpan();
        string absolutePath = span.Path;
        int line = span.StartLinePosition.Line + 1; // 0-based 转 1-based
        string relativePath = NormalizePath(absolutePath);
        string memberName = FindEnclosingMemberName(invocation);

        return new InterceptionTarget(
            MethodName: op.TargetMethod.Name,
            Location: location,
            RelativePath: relativePath,
            Line: line,
            MemberName: memberName);
    }

    /// <summary>生成拦截器源代码（每个调用点一个拦截方法）。</summary>
    public static string Generate(ImmutableArray<InterceptionTarget?> targets)
    {
        var sb = new System.Text.StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        // InterceptsLocationAttribute 必须定义在 System.Runtime.CompilerServices——编译器硬编码要求。
        // 拦截器类型放 PalORM.Generated（需在 InterceptorsNamespaces 声明）。
        // 用两个 block namespace（非 file-scoped）避免 CS8954（文件只能含一个 file-scoped namespace）。
        sb.AppendLine("namespace System.Runtime.CompilerServices");
        sb.AppendLine("{");
        sb.AppendLine("    [System.AttributeUsage(System.AttributeTargets.Method, AllowMultiple = true)]");
        sb.AppendLine("    internal sealed class InterceptsLocationAttribute : System.Attribute");
        sb.AppendLine("    {");
        sb.AppendLine("        public InterceptsLocationAttribute(int version, string data) { }");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("namespace PalORM.Generated");
        sb.AppendLine("{");
        sb.AppendLine("    " + GeneratedCodeMetadata.GeneratedCodeAttribute);
        sb.AppendLine("    internal static class AutoTaggingInterceptor");
        sb.AppendLine("    {");

        int index = 0;
        foreach (InterceptionTarget? target in targets)
        {
            if (target is null) continue;
            // 评审 2026-09-02：IsTerminalCall 已按同一清单过滤方法名——TryGetReturnType 未命中
            // 仅可能是管道回归。原 throw 让用户收到 CS8785 生成器崩溃；改为跳过该调用点
            // （无拦截器 = 该调用无自动标签），fail-safe 优于 crash。
            if (!TryGetReturnType(target.MethodName, out string returnType)) continue;
            AppendInterceptorMethod(sb, target, returnType, index);
            sb.AppendLine();
            index++;
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    /// <summary>为单个调用点生成拦截方法。</summary>
    private static void AppendInterceptorMethod(
        System.Text.StringBuilder sb, InterceptionTarget target, string returnType, int index)
    {
        // [InterceptsLocation(version, data)] —— data 来自 GetInterceptableLocation，不可手写。
        // GetInterceptsLocationAttributeSyntax 输出 global::System.Runtime.CompilerServices.InterceptsLocationAttribute(version, data)。
        sb.AppendLine($"        {target.Location.GetInterceptsLocationAttributeSyntax()}");

        // Tag 注释内容：文件名:行号 成员名（ITM-697：恒文件名，构建确定性）
        string tag = $"{target.RelativePath}:{target.Line} {target.MemberName}";
        // ITM-631：拦截 `*/`（Linux 文件名可含 *）——tag 进入 SQL 块注释，
        // 未转义的 */ 会被运行时 ValidateSqlComment 拒绝且报错远根因。插空格防闭合。
        // ITM-645：`/*` 同理——ValidateSqlComment 双向拒绝（注释开启/闭合定界符），
        // 发送侧与接收侧契约对称：这里也插空格防开启定界。
        string escapedTag = tag
            .Replace("*/", "* /")
            .Replace("/*", "/ *")
            .Replace("\\", "\\\\")
            .Replace("\"", "\\\"")
            // ITM-669：C# 字符串字面量非法/破坏性字符——极端文件名（含换行/制表）不得
            // 破坏生成源；转义为 \n \t \r 字面量（同时避免 SQL 注释内的裸控制符）。
            // ITM-742(r20)：补 C# new_line_character 家族其余成员（U+0085 NEL / U+2028 LS /
            // U+2029 PS）——与 \n 同属 C# 规范行终止符，裸置会使字面量跨行而编译失败。
            .Replace("\r", "\\r")
            .Replace("\n", "\\n")
            .Replace("\t", "\\t")
            .Replace("\u0085", "\\u0085")
            .Replace("\u2028", "\\u2028")
            .Replace("\u2029", "\\u2029");

        // 方法签名：统一参数 (this QueryBuilder<T> builder, CancellationToken ct = default) + where T : class, new()
        sb.AppendLine($"        internal static async {returnType}");
        sb.AppendLine($"            {target.MethodName}_AutoTag_{index}<T>(this global::PalORM.QueryBuilder<T> builder,");
        sb.AppendLine($"                global::System.Threading.CancellationToken ct = default)");
        sb.AppendLine($"            where T : class, new()");
        sb.AppendLine("        {");
        sb.AppendLine($"            return await builder.Tag(\"{escapedTag}\").{target.MethodName}(ct).ConfigureAwait(false);");
        sb.AppendLine("        }");
    }

    /// <summary>根据方法名查返回类型（签名匹配用）。</summary>
    private static bool TryGetReturnType(string methodName, out string returnType)
    {
        foreach (var terminal in s_terminals)
        {
            if (terminal.Name == methodName)
            {
                returnType = terminal.ReturnType;
                return true;
            }
        }
        // 不应到达——IsTerminalCall 已按同一清单过滤（Generate 侧 fail-safe 跳过，见该处注释）
        returnType = "";
        return false;
    }

    /// <summary>
    /// 路径规范化：绝对路径 → 仅文件名（确定性）。
    /// 避免编译机绝对路径泄露到 DB 日志（TagWithCaller 的已知限制）。
    /// r19/ITM-697：不再以 GetCurrentDirectory 为基准剥前缀——不同 CWD 构建会产出
    /// 不同的相对路径 Tag（生成源非确定性）；恒返回文件名，构建可复现。
    /// </summary>
    private static string NormalizePath(string absolutePath)
    {
        if (string.IsNullOrEmpty(absolutePath)) return "unknown";
        return System.IO.Path.GetFileName(absolutePath);
    }

    /// <summary>从调用点向上查找包含的成员名（方法/属性/局部函数）。</summary>
    private static string FindEnclosingMemberName(SyntaxNode node)
    {
        SyntaxNode? current = node.Parent;
        while (current is not null)
        {
            if (current is MethodDeclarationSyntax method)
                return method.Identifier.Text;
            if (current is PropertyDeclarationSyntax prop)
                return prop.Identifier.Text;
            // ITM-631：局部函数是最常见的仓储封装形态——此前标签恒为 unknown 丢失定位
            if (current is Microsoft.CodeAnalysis.CSharp.Syntax.LocalFunctionStatementSyntax local)
                return local.Identifier.Text;
            current = current.Parent;
        }
        return "unknown";
    }

    /// <summary>终态方法定义（方法名 + 返回类型）。</summary>
    private readonly record struct TerminalMethod(string Name, string ReturnType);

    /// <summary>
    /// 拦截目标。增量缓存相等性（审计 GEN-014 修正注释）：成员 <see cref="InterceptableLocation"/>
    /// 是 Roslyn 类型且未重写 Equals——record 合成相等对它退化为<b>引用相等</b>，
    /// 故 <c>WithComparer(Default)</c> 实际按引用比较，候选节点一变即整体重渲染
    /// PalORM_AutoTagging.g.cs。方向安全（只过度失效、不漏失效），非值相等命中。
    /// </summary>
    public sealed record InterceptionTarget(
        string MethodName,
        InterceptableLocation Location,
        string RelativePath,
        int Line,
        string MemberName);
}
