// v5.1 Auto Tagging Interceptor：扫描 9 个终态方法调用（ITM-818 补齐 ForEachAsync/ToPageAsync/
// QueryMultipleAsync 后由 6 扩至 9——ITM-909 同步三处头注），生成 [InterceptsLocation] 拦截方法。
// 拦截方法体注入 builder.Tag(\"relativePath:line member\")，自动给 SQL 加源码定位注释。
// ITM-775(r21)：删除头部残留的 // <auto-generated/> 与文件级 CS1591 抑制——本文件是
// Emitter 源码（全 SourceGen 唯一带生成物头部模板）；auto-generated 标记会让分析器把
// 本文件按生成代码跳过诊断，CS1591 对 internal 类型无效且属禁止清单 #9 的削弱型抑制。
#nullable enable

using System.Collections.Immutable;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Operations;

namespace PalORM.SourceGen;

/// <summary>
/// Auto Tagging Interceptor 生成器：扫描 9 个终态方法调用，生成 [InterceptsLocation] 拦截方法。
/// </summary>
/// <remarks>
/// <b>工作原理</b>：源生成器在编译期检测 <c>QueryBuilderExtensions</c> 的 9 个终态方法调用，
/// 为每个调用点生成一个拦截方法。拦截方法体注入 <c>builder.Tag(...)</c> 后调用原方法，
/// 实现"用户零代码改动，SQL 自动带源码定位注释"。<br/>
/// <b>opt-in 开关</b>：消费侧 csproj 设置 <c>&lt;PalORMAutoTagging&gt;true&lt;/PalORMAutoTagging&gt;</c> 启用。
/// </remarks>
internal static class AutoTaggingEmitter
{
    /// <summary>
    /// 9 个终态方法定义：方法名 → 返回类型/类型参数/参数列表/转发实参（用于生成签名
    /// 匹配的拦截方法）。
    /// <b>ITM-909 双源风险</b>：本表是 Core QueryBuilderExtensions 签名的第二真源——
    /// Core 侧改签名/新增终态时须同步此表（哨兵测试 AutoTaggingTests 九终态全部被拦截锁
    /// 覆盖面；新增终态时扩该测试）。
    /// <b>ITM-914（r24，哨兵测试揭穿）</b>：原模型只有 Name+ReturnType，签名模板硬编码
    /// <c>&lt;T&gt;</c> + 统一两参——ToPageAsync（双泛型 &lt;T, TKey&gt;、6 参）从未被拦截，
    /// ForEachAsync/QueryMultipleAsync 的转发调用参数不全（生成物编译错误风险）。
    /// 本轮模板化：类型参数/参数列表/转发实参逐终态显式声明，与 Core 第一真源逐位对齐。
    /// </summary>
    private static readonly ImmutableArray<TerminalMethod> s_terminals = new[]
    {
        new TerminalMethod("ToListAsync", "global::System.Threading.Tasks.ValueTask<global::System.Collections.Generic.List<T>>"),
        new TerminalMethod("FirstAsync", "global::System.Threading.Tasks.ValueTask<T>"),
        new TerminalMethod("FirstOrDefaultAsync", "global::System.Threading.Tasks.ValueTask<T?>"),
        new TerminalMethod("SingleAsync", "global::System.Threading.Tasks.ValueTask<T>"),
        new TerminalMethod("SingleOrDefaultAsync", "global::System.Threading.Tasks.ValueTask<T?>"),
        new TerminalMethod("ExecuteNonQueryAsync", "global::System.Threading.Tasks.ValueTask<int>"),
        // ITM-818（r23 实修）：补齐三个漏登记的终态——此前这些调用点 SQL 无源码定位注释，
        // 与自动加定位注释的承诺不一致（ForEachAsync/ToPageAsync/QueryMultipleAsync）。
        // ITM-914：三者的签名模板此前缺失（模板化补全）。
        new TerminalMethod("ForEachAsync", "global::System.Threading.Tasks.ValueTask<long>",
            Params: "(this global::PalORM.QueryBuilder<T> builder, global::System.Func<T, global::System.Threading.CancellationToken, global::System.Threading.Tasks.ValueTask> action, global::System.Threading.CancellationToken ct = default)",
            ForwardArgs: "action, ct"),
        new TerminalMethod("ToPageAsync", "global::System.Threading.Tasks.ValueTask<(global::System.Collections.Generic.List<T> Rows, long Total)>",
            TypeParams: "<T, TKey>",
            Params: "(this global::PalORM.QueryBuilder<T> builder, int pageSize, global::System.Linq.Expressions.Expression<global::System.Func<T, TKey>> orderBy, TKey? lastValue = default, bool descending = true, global::System.Threading.CancellationToken ct = default)",
            ForwardArgs: "pageSize, orderBy, lastValue, descending, ct"),
        new TerminalMethod("QueryMultipleAsync", "global::System.Threading.Tasks.ValueTask<PalORM.GridReader>",
            Params: "(this global::PalORM.QueryBuilder<T> builder, global::System.FormattableString sql, global::System.Threading.CancellationToken ct = default)",
            ForwardArgs: "sql, ct"),
    }.ToImmutableArray();

    /// <summary>谓词：节点是 9 个终态方法之一的 InvocationExpression。</summary>
    public static bool IsTerminalCall(SyntaxNode node)
    {
        if (node is not InvocationExpressionSyntax invocation
            || invocation.Expression is not MemberAccessExpressionSyntax member)
            return false;
        string name = member.Name.Identifier.Text;
        foreach (var terminal in s_terminals)
        {
            if (name == terminal.Name) return true;
        }
        return false;
    }

    /// <summary>转换：提取调用点的 InterceptableLocation + 路径/行号/方法名。</summary>
    public static InterceptionTarget? ExtractTarget(GeneratorSyntaxContext ctx, CancellationToken ct)
    {
        var invocation = (InvocationExpressionSyntax)ctx.Node;
        if (ctx.SemanticModel.GetOperation(invocation, ct) is not IInvocationOperation op)
            return null;
        // 过滤：必须是 PalORM.QueryBuilderExtensions 的方法（排除其他同名方法）。
        // ITM-631：裸类名比对可被用户自定义同名静态类穿透——命名空间全限定精确匹配。
        if (op.TargetMethod.ContainingType is not { Name: "QueryBuilderExtensions" } containingType
            || containingType.ContainingNamespace?.ToDisplayString() != "PalORM")
            return null;
        // ITM-818（r23 实修）：以符号的 OriginalDefinition 名复核终态身份——方法组/泛型构造
        // 形态下语法层同名不保证是终态本体，误判会在生成物上挂 [InterceptsLocation] 失败
        //（CS8849 类编译错误，报错点落在生成物内难归因）。
        string symbolName = op.TargetMethod.OriginalDefinition.Name;
        bool isKnownTerminal = false;
        foreach (var terminal in s_terminals)
        {
            if (symbolName == terminal.Name) { isKnownTerminal = true; break; }
        }
        if (!isKnownTerminal) return null;

        // GetInterceptableLocation 扩展方法（CSharpExtensions 提供）
        InterceptableLocation? location = ctx.SemanticModel.GetInterceptableLocation(invocation, ct);
        if (location is null) return null;

        // 提取调用点位置信息（用于 Tag 注释）
        Location loc = invocation.GetLocation();
        FileLinePositionSpan span = loc.GetLineSpan();
        string absolutePath = span.Path;
        int line = span.StartLinePosition.Line + 1; // 0-based 转 1-based
        string relativePath = NormalizePath(absolutePath);
        string memberName = FindEnclosingMemberName(invocation);

        return new InterceptionTarget(
            MethodName: op.TargetMethod.Name,
            Location: location,
            RelativePath: relativePath,
            Line: line,
            MemberName: memberName);
    }

    /// <summary>生成拦截器源代码（每个调用点一个拦截方法）。</summary>
    public static string Generate(ImmutableArray<InterceptionTarget?> targets)
    {
        var sb = new System.Text.StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        // InterceptsLocationAttribute 必须定义在 System.Runtime.CompilerServices——编译器硬编码要求。
        // 拦截器类型放 PalORM.Generated（需在 InterceptorsNamespaces 声明）。
        // 用两个 block namespace（非 file-scoped）避免 CS8954（文件只能含一个 file-scoped namespace）。
        sb.AppendLine("namespace System.Runtime.CompilerServices");
        sb.AppendLine("{");
        sb.AppendLine("    [System.AttributeUsage(System.AttributeTargets.Method, AllowMultiple = true)]");
        sb.AppendLine("    internal sealed class InterceptsLocationAttribute : System.Attribute");
        sb.AppendLine("    {");
        sb.AppendLine("        public InterceptsLocationAttribute(int version, string data) { }");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("namespace PalORM.Generated");
        sb.AppendLine("{");
        sb.AppendLine("    " + GeneratedCodeMetadata.GeneratedCodeAttribute);
        sb.AppendLine("    internal static class AutoTaggingInterceptor");
        sb.AppendLine("    {");

        int index = 0;
        foreach (InterceptionTarget? target in targets)
        {
            if (target is null) continue;
            // 评审 2026-09-02：IsTerminalCall 已按同一清单过滤方法名——未命中仅可能是管道
            // 回归。原 throw 让用户收到 CS8785 生成器崩溃；改为跳过该调用点
            // （无拦截器 = 该调用无自动标签），fail-safe 优于 crash。
            if (!TryGetTerminal(target.MethodName, out TerminalMethod terminal)) continue;
            AppendInterceptorMethod(sb, target, terminal, index);
            sb.AppendLine();
            index++;
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    /// <summary>为单个调用点生成拦截方法。</summary>
    private static void AppendInterceptorMethod(
        System.Text.StringBuilder sb, InterceptionTarget target, TerminalMethod terminal, int index)
    {
        // [InterceptsLocation(version, data)] —— data 来自 GetInterceptableLocation，不可手写。
        // GetInterceptsLocationAttributeSyntax 输出 global::System.Runtime.CompilerServices.InterceptsLocationAttribute(version, data)。
        sb.AppendLine($"        {target.Location.GetInterceptsLocationAttributeSyntax()}");

        // Tag 注释内容：文件名:行号 成员名（ITM-697：恒文件名，构建确定性）
        string tag = $"{target.RelativePath}:{target.Line} {target.MemberName}";
        // ITM-631：拦截 `*/`（Linux 文件名可含 *）——tag 进入 SQL 块注释，
        // 未转义的 */ 会被运行时 ValidateSqlComment 拒绝且报错远根因。插空格防闭合。
        // ITM-645：`/*` 同理——ValidateSqlComment 双向拒绝（注释开启/闭合定界符），
        // 发送侧与接收侧契约对称：这里也插空格防开启定界。
        string escapedTag = tag
            .Replace("*/", "* /")
            .Replace("/*", "/ *")
            .Replace("\\", "\\\\")
            .Replace("\"", "\\\"")
            // ITM-669：C# 字符串字面量非法/破坏性字符——极端文件名（含换行/制表）不得
            // 破坏生成源；转义为 \n \t \r 字面量（同时避免 SQL 注释内的裸控制符）。
            // ITM-742(r20)：补 C# new_line_character 家族其余成员（U+0085 NEL / U+2028 LS /
            // U+2029 PS）——与 \n 同属 C# 规范行终止符，裸置会使字面量跨行而编译失败。
            .Replace("\r", "\\r")
            .Replace("\n", "\\n")
            .Replace("\t", "\\t")
            .Replace("\u0085", "\\u0085")
            .Replace("\u2028", "\\u2028")
            .Replace("\u2029", "\\u2029");

        // ITM-914（r24）：签名逐终态模板化——类型参数/参数列表/约束/转发实参全部来自
        // TerminalMethod（s_terminals 与 Core 第一真源对齐）；原硬编码 <T> 两参模板对
        // 多参/双泛型终态（ToPageAsync）静默漏拦截、对转发调用参数不全。
        sb.AppendLine($"        internal static async {terminal.ReturnType}");
        sb.AppendLine($"            {target.MethodName}_AutoTag_{index}{terminal.TypeParams}{terminal.Params}");
        sb.AppendLine($"            {terminal.Constraints}");
        sb.AppendLine("        {");
        sb.AppendLine($"            return await builder.Tag(\"{escapedTag}\").{target.MethodName}({terminal.ForwardArgs}).ConfigureAwait(false);");
        sb.AppendLine("        }");
    }

    /// <summary>根据方法名查终态定义（签名匹配用）。</summary>
    private static bool TryGetTerminal(string methodName, out TerminalMethod terminal)
    {
        foreach (TerminalMethod t in s_terminals)
        {
            if (t.Name == methodName)
            {
                terminal = t;
                return true;
            }
        }
        // 不应到达——IsTerminalCall 已按同一清单过滤（Generate 侧 fail-safe 跳过，见该处注释）
        terminal = default;
        return false;
    }

    /// <summary>
    /// 路径规范化：绝对路径 → 仅文件名（确定性）。
    /// 避免编译机绝对路径泄露到 DB 日志（TagWithCaller 的已知限制）。
    /// r19/ITM-697：不再以 GetCurrentDirectory 为基准剥前缀——不同 CWD 构建会产出
    /// 不同的相对路径 Tag（生成源非确定性）；恒返回文件名，构建可复现。
    /// </summary>
    private static string NormalizePath(string absolutePath)
    {
        if (string.IsNullOrEmpty(absolutePath)) return "unknown";
        return System.IO.Path.GetFileName(absolutePath);
    }

    /// <summary>从调用点向上查找包含的成员名（方法/属性/局部函数）。</summary>
    private static string FindEnclosingMemberName(SyntaxNode node)
    {
        SyntaxNode? current = node.Parent;
        while (current is not null)
        {
            if (current is MethodDeclarationSyntax method)
                return method.Identifier.Text;
            if (current is PropertyDeclarationSyntax prop)
                return prop.Identifier.Text;
            // ITM-631：局部函数是最常见的仓储封装形态——此前标签恒为 unknown 丢失定位
            if (current is Microsoft.CodeAnalysis.CSharp.Syntax.LocalFunctionStatementSyntax local)
                return local.Identifier.Text;
            current = current.Parent;
        }
        return "unknown";
    }

    /// <summary>终态方法定义（方法名 + 返回类型）。</summary>
    /// <summary>终态方法定义（ITM-914 模板化：签名三要素显式声明，与 Core 第一真源对齐）。</summary>
    private readonly record struct TerminalMethod(
        string Name,
        string ReturnType,
        string TypeParams = "<T>",
        string Params = "(this global::PalORM.QueryBuilder<T> builder, global::System.Threading.CancellationToken ct = default)",
        string Constraints = "where T : class, new()",
        string ForwardArgs = "ct");

    /// <summary>
    /// 拦截目标。增量缓存相等性（审计 GEN-014 修正注释）：成员 <see cref="InterceptableLocation"/>
    /// 是 Roslyn 类型且未重写 Equals——record 合成相等对它退化为<b>引用相等</b>，
    /// 故 <c>WithComparer(Default)</c> 实际按引用比较，候选节点一变即整体重渲染
    /// PalORM_AutoTagging.g.cs。方向安全（只过度失效、不漏失效），非值相等命中。
    /// </summary>
    public sealed record InterceptionTarget(
        string MethodName,
        InterceptableLocation Location,
        string RelativePath,
        int Line,
        string MemberName);
}
