// <auto-generated/>
// v5.1 Auto Tagging Interceptor：扫描 6 个终态方法调用，生成 [InterceptsLocation] 拦截方法。
// 拦截方法体注入 builder.Tag(\"relativePath:line member\")，自动给 SQL 加源码定位注释。
#pragma warning disable RS1035 // 源生成器禁止 IO API — 本文件做受控 IO：NormalizePath 读 Directory.GetCurrentDirectory() 做路径归一化（ITM-631：原“不执行 IO”声明与实现矛盾，已更正）
#pragma warning disable CS1591 // 缺少 XML 注释
#nullable enable

using System.Collections.Immutable;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Operations;

namespace PalORM.SourceGen;

/// <summary>
/// Auto Tagging Interceptor 生成器：扫描 6 个终态方法调用，生成 [InterceptsLocation] 拦截方法。
/// </summary>
/// <remarks>
/// <b>工作原理</b>：源生成器在编译期检测 <c>QueryBuilderExtensions</c> 的 6 个终态方法调用，
/// 为每个调用点生成一个拦截方法。拦截方法体注入 <c>builder.Tag(...)</c> 后调用原方法，
/// 实现"用户零代码改动，SQL 自动带源码定位注释"。<br/>
/// <b>opt-in 开关</b>：消费侧 csproj 设置 <c>&lt;PalORMAutoTagging&gt;true&lt;/PalORMAutoTagging&gt;</c> 启用。
/// </remarks>
internal static class AutoTaggingEmitter
{
    /// <summary>
    /// 6 个终态方法定义：方法名 → 返回类型（用于生成签名匹配的拦截方法）。
    /// 签名差异仅在返回类型；参数列表统一为 (this QueryBuilder&lt;T&gt; builder, CancellationToken ct = default)。
    /// </summary>
    private static readonly ImmutableArray<TerminalMethod> s_terminals = new[]
    {
        new TerminalMethod("ToListAsync", "global::System.Threading.Tasks.ValueTask<global::System.Collections.Generic.List<T>>"),
        new TerminalMethod("FirstAsync", "global::System.Threading.Tasks.ValueTask<T>"),
        new TerminalMethod("FirstOrDefaultAsync", "global::System.Threading.Tasks.ValueTask<T?>"),
        new TerminalMethod("SingleAsync", "global::System.Threading.Tasks.ValueTask<T>"),
        new TerminalMethod("SingleOrDefaultAsync", "global::System.Threading.Tasks.ValueTask<T?>"),
        new TerminalMethod("ExecuteNonQueryAsync", "global::System.Threading.Tasks.ValueTask<int>"),
    }.ToImmutableArray();

    /// <summary>谓词：节点是 6 个终态方法之一的 InvocationExpression。</summary>
    public static bool IsTerminalCall(SyntaxNode node)
    {
        if (node is not InvocationExpressionSyntax invocation
            || invocation.Expression is not MemberAccessExpressionSyntax member)
            return false;
        string name = member.Name.Identifier.Text;
        foreach (var terminal in s_terminals)
        {
            if (name == terminal.Name) return true;
        }
        return false;
    }

    /// <summary>转换：提取调用点的 InterceptableLocation + 路径/行号/方法名。</summary>
    public static InterceptionTarget? ExtractTarget(GeneratorSyntaxContext ctx, CancellationToken ct)
    {
        var invocation = (InvocationExpressionSyntax)ctx.Node;
        if (ctx.SemanticModel.GetOperation(invocation, ct) is not IInvocationOperation op)
            return null;
        // 过滤：必须是 PalORM.QueryBuilderExtensions 的方法（排除其他同名方法）。
        // ITM-631：裸类名比对可被用户自定义同名静态类穿透——命名空间全限定精确匹配。
        if (op.TargetMethod.ContainingType is not { Name: "QueryBuilderExtensions" } containingType
            || containingType.ContainingNamespace?.ToDisplayString() != "PalORM")
            return null;

        // GetInterceptableLocation 扩展方法（CSharpExtensions 提供）
        InterceptableLocation? location = ctx.SemanticModel.GetInterceptableLocation(invocation, ct);
        if (location is null) return null;

        // 提取调用点位置信息（用于 Tag 注释）
        Location loc = invocation.GetLocation();
        FileLinePositionSpan span = loc.GetLineSpan();
        string absolutePath = span.Path;
        int line = span.StartLinePosition.Line + 1; // 0-based 转 1-based
        string relativePath = NormalizePath(absolutePath);
        string memberName = FindEnclosingMemberName(invocation);

        return new InterceptionTarget(
            MethodName: op.TargetMethod.Name,
            Location: location,
            RelativePath: relativePath,
            Line: line,
            MemberName: memberName);
    }

    /// <summary>生成拦截器源代码（每个调用点一个拦截方法）。</summary>
    public static string Generate(ImmutableArray<InterceptionTarget?> targets)
    {
        var sb = new System.Text.StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        // InterceptsLocationAttribute 必须定义在 System.Runtime.CompilerServices——编译器硬编码要求。
        // 拦截器类型放 PalORM.Generated（需在 InterceptorsNamespaces 声明）。
        // 用两个 block namespace（非 file-scoped）避免 CS8954（文件只能含一个 file-scoped namespace）。
        sb.AppendLine("namespace System.Runtime.CompilerServices");
        sb.AppendLine("{");
        sb.AppendLine("    [System.AttributeUsage(System.AttributeTargets.Method, AllowMultiple = true)]");
        sb.AppendLine("    internal sealed class InterceptsLocationAttribute : System.Attribute");
        sb.AppendLine("    {");
        sb.AppendLine("        public InterceptsLocationAttribute(int version, string data) { }");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("namespace PalORM.Generated");
        sb.AppendLine("{");
        sb.AppendLine("    [global::System.CodeDom.Compiler.GeneratedCode(\"PalORM.SourceGen\", \"2.0.0\")]");
        sb.AppendLine("    internal static class AutoTaggingInterceptor");
        sb.AppendLine("    {");

        int index = 0;
        foreach (InterceptionTarget? target in targets)
        {
            if (target is null) continue;
            AppendInterceptorMethod(sb, target, index);
            sb.AppendLine();
            index++;
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    /// <summary>为单个调用点生成拦截方法。</summary>
    private static void AppendInterceptorMethod(System.Text.StringBuilder sb, InterceptionTarget target, int index)
    {
        // [InterceptsLocation(version, data)] —— data 来自 GetInterceptableLocation，不可手写。
        // GetInterceptsLocationAttributeSyntax 输出 global::System.Runtime.CompilerServices.InterceptsLocationAttribute(version, data)。
        sb.AppendLine($"        {target.Location.GetInterceptsLocationAttributeSyntax()}");

        // 查找方法的返回类型（签名必须逐字匹配被拦截方法，否则 CS9144）
        string returnType = GetReturnType(target.MethodName);

        // Tag 注释内容：文件名:行号 成员名（ITM-697：恒文件名，构建确定性）
        string tag = $"{target.RelativePath}:{target.Line} {target.MemberName}";
        // ITM-631：拦截 `*/`（Linux 文件名可含 *）——tag 进入 SQL 块注释，
        // 未转义的 */ 会被运行时 ValidateSqlComment 拒绝且报错远根因。插空格防闭合。
        // ITM-645：`/*` 同理——ValidateSqlComment 双向拒绝（注释开启/闭合定界符），
        // 发送侧与接收侧契约对称：这里也插空格防开启定界。
        string escapedTag = tag
            .Replace("*/", "* /")
            .Replace("/*", "/ *")
            .Replace("\\", "\\\\")
            .Replace("\"", "\\\"")
            // ITM-669：C# 字符串字面量非法/破坏性字符——极端文件名（含换行/制表）不得
            // 破坏生成源；转义为 \n \t \r 字面量（同时避免 SQL 注释内的裸控制符）。
            .Replace("\r", "\\r")
            .Replace("\n", "\\n")
            .Replace("\t", "\\t");

        // 方法签名：统一参数 (this QueryBuilder<T> builder, CancellationToken ct = default) + where T : class, new()
        sb.AppendLine($"        internal static async {returnType}");
        sb.AppendLine($"            {target.MethodName}_AutoTag_{index}<T>(this global::PalORM.QueryBuilder<T> builder,");
        sb.AppendLine($"                global::System.Threading.CancellationToken ct = default)");
        sb.AppendLine($"            where T : class, new()");
        sb.AppendLine("        {");
        sb.AppendLine($"            return await builder.Tag(\"{escapedTag}\").{target.MethodName}(ct).ConfigureAwait(false);");
        sb.AppendLine("        }");
    }

    /// <summary>根据方法名查返回类型（签名匹配用）。</summary>
    private static string GetReturnType(string methodName)
    {
        foreach (var terminal in s_terminals)
        {
            if (terminal.Name == methodName) return terminal.ReturnType;
        }
        // 不应到达——IsTerminalCall 已过滤
        throw new System.InvalidOperationException($"Unknown terminal method: {methodName}");
    }

    /// <summary>
    /// 路径规范化：绝对路径 → 仅文件名（确定性）。
    /// 避免编译机绝对路径泄露到 DB 日志（TagWithCaller 的已知限制）。
    /// r19/ITM-697：不再以 GetCurrentDirectory 为基准剥前缀——不同 CWD 构建会产出
    /// 不同的相对路径 Tag（生成源非确定性）；恒返回文件名，构建可复现。
    /// </summary>
    private static string NormalizePath(string absolutePath)
    {
        if (string.IsNullOrEmpty(absolutePath)) return "unknown";
        return System.IO.Path.GetFileName(absolutePath);
    }

    /// <summary>从调用点向上查找包含的成员名（方法/属性/局部函数）。</summary>
    private static string FindEnclosingMemberName(SyntaxNode node)
    {
        SyntaxNode? current = node.Parent;
        while (current is not null)
        {
            if (current is MethodDeclarationSyntax method)
                return method.Identifier.Text;
            if (current is PropertyDeclarationSyntax prop)
                return prop.Identifier.Text;
            // ITM-631：局部函数是最常见的仓储封装形态——此前标签恒为 unknown 丢失定位
            if (current is Microsoft.CodeAnalysis.CSharp.Syntax.LocalFunctionStatementSyntax local)
                return local.Identifier.Text;
            current = current.Parent;
        }
        return "unknown";
    }

    /// <summary>终态方法定义（方法名 + 返回类型）。</summary>
    private readonly record struct TerminalMethod(string Name, string ReturnType);

    /// <summary>
    /// 拦截目标（sealed record，值相等用于增量缓存命中）。
    /// </summary>
    public sealed record InterceptionTarget(
        string MethodName,
        InterceptableLocation Location,
        string RelativePath,
        int Line,
        string MemberName);
}
