using System.Text;

namespace PalORM.SourceGen;

internal static class CommandFactoryEmitter
{
    internal static string Generate(TableModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace PalORM.Generated;");
        sb.AppendLine();
        sb.AppendLine($"internal static class CommandFactory_{model.GeneratedTypeSuffix}");
        sb.AppendLine("{");
        foreach (var column in model.Columns.AsSpan())
        {
            if (!IsObjectOwnedJson(column)) continue;
            sb.AppendLine($"    internal static readonly global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<{column.ClrTypeName}> JsonTypeInfo_{column.PropertyName} = (global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<{column.ClrTypeName}>)({column.OwnedJsonContextTypeName}.Default.GetTypeInfo(typeof({column.ClrTypeName})) ?? throw new global::System.InvalidOperationException(\"OwnedJson type metadata was not generated.\"));");
        }
        sb.AppendLine($"    internal const string InsertSql = {MigrationEmitter.ToCSharpLiteral(BuildInsertSql(model))};");
        sb.AppendLine($"    internal const string UpdateSql = {MigrationEmitter.ToCSharpLiteral(BuildUpdateSql(model))};");
        sb.AppendLine($"    internal const string DeleteSql = {MigrationEmitter.ToCSharpLiteral(BuildDeleteSql(model))};");
        sb.AppendLine($"    internal const string InsertReturningSql = {MigrationEmitter.ToCSharpLiteral(BuildInsertReturningSql(model))};");
        sb.AppendLine();
        sb.AppendLine($"    /// <summary>绑定实体属性到 INSERT 参数。</summary>");
        sb.AppendLine($"    internal static void BindInsert(global::System.Data.Common.DbCommand cmd, {model.EntityTypeName} entity)");
        sb.AppendLine("    {");
        GenerateBindInsertBody(model, sb);
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine($"    /// <summary>绑定实体属性到 UPSERT 参数，包含主键。</summary>");
        sb.AppendLine($"    internal static void BindUpsert(global::System.Data.Common.DbCommand cmd, {model.EntityTypeName} entity)");
        sb.AppendLine("    {");
        GenerateBindUpsertBody(model, sb);
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine($"    /// <summary>绑定实体属性到 UPDATE 参数。</summary>");
        sb.AppendLine($"    internal static void BindUpdate(global::System.Data.Common.DbCommand cmd, {model.EntityTypeName} entity)");
        sb.AppendLine("    {");
        GenerateBindUpdateBody(model, sb);
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine($"    /// <summary>绑定主键到 DELETE 参数。</summary>");
        sb.AppendLine($"    internal static void BindDelete(global::System.Data.Common.DbCommand cmd, object key)");
        sb.AppendLine("    {");
        GenerateBindDeleteBody(model, sb);
        sb.AppendLine("    }");
        sb.AppendLine();
        // BindInsertValues: 零 DbCommand 路径，BulkInsert 用
        sb.AppendLine($"    internal static void BindInsertValues(global::System.Collections.Generic.List<(string Name, object? Value)> list, {model.EntityTypeName} entity)");
        sb.AppendLine("    {");
        GenerateBindInsertValuesBody(model, sb);
        sb.AppendLine("    }");
        sb.AppendLine();
        // SetId: 编译时安全设置自增主键（零反射，替代 MySQL LAST_INSERT_ID 后 Type.GetProperties()）
        sb.AppendLine($"    internal static void SetId({model.EntityTypeName} entity, long id)");
        sb.AppendLine("    {");
        GenerateSetIdBody(model, sb);
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine($"    internal static void IncrementVersion({model.EntityTypeName} entity)");
        sb.AppendLine("    {");
        GenerateIncrementVersionBody(model, sb);
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine($"    internal static bool HasDefaultKey({model.EntityTypeName} entity)");
        sb.AppendLine("    {");
        GenerateHasDefaultKeyBody(model, sb);
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void GenerateBindDeleteBody(TableModel model, StringBuilder sb)
    {
        var pkCols = model.Columns.AsSpan().ToArray().Where(c => c.IsPrimaryKey).ToArray();
        int pi = 0;
        foreach (var col in pkCols)
        {
            string castExpr = col.ConverterTypeName is not null
                ? $"({col.ClrTypeName})key"
                : col.ClrTypeName switch
            {
                _ when col.ClrTypeName.EndsWith("Int64") || col.ClrTypeName.EndsWith("long") => $"((long)key)",
                _ when col.ClrTypeName.EndsWith("Int32") || col.ClrTypeName.EndsWith("int") => $"((int)key)",
                _ when col.ClrTypeName.EndsWith("String") || col.ClrTypeName.EndsWith("string") => $"((string)key)",
                _ when col.ClrTypeName.EndsWith("Guid") => $"((global::System.Guid)key)",
                _ => $"key"
            };
            string providerValueExpr = col.ConverterTypeName is null
                ? castExpr
                : $"(({GetConverterInterfaceType(col)})new {col.ConverterTypeName}()).ToProvider({castExpr})";
            string valueExpr = col.IsNullable
                ? $"{castExpr} is null ? global::System.DBNull.Value : (object){providerValueExpr}"
                : $"(object){providerValueExpr}";
            sb.AppendLine($"        {{ var p = cmd.CreateParameter(); p.ParameterName = \"@p{pi}\"; p.Value = {valueExpr}; cmd.Parameters.Add(p); }}");
            pi++;
        }
    }

    private static void GenerateBindInsertValuesBody(TableModel model, StringBuilder sb)
    {
        int pi = 0;
        foreach (var col in model.Columns.AsSpan())
        {
            if (!col.IsInsertable) continue;
            string valueExpr = GetParameterValueExpression(col);
            sb.AppendLine($"        list.Add((\"@p{pi}\", {valueExpr}));");
            pi++;
        }
    }

    private static void GenerateBindUpsertBody(TableModel model, StringBuilder sb)
    {
        int pi = 0;
        foreach (var col in model.Columns.AsSpan())
        {
            if (!col.IsUpsertable) continue;
            string valueExpr = GetParameterValueExpression(col);
            sb.AppendLine($"        {{ var p = cmd.CreateParameter(); p.ParameterName = \"@p{pi}\"; p.Value = {valueExpr}; cmd.Parameters.Add(p); }}");
            pi++;
        }
    }

    private static void GenerateHasDefaultKeyBody(TableModel model, StringBuilder sb)
    {
        var pkColumn = model.Columns.AsSpan().ToArray().FirstOrDefault(c => c.IsPrimaryKey);
        if (pkColumn is null)
        {
            sb.AppendLine("        return true;");
            return;
        }
        sb.AppendLine($"        return global::System.Collections.Generic.EqualityComparer<{pkColumn.ClrTypeName}>.Default.Equals(entity.{pkColumn.PropertyName}, default);");
    }

    private static void GenerateIncrementVersionBody(TableModel model, StringBuilder sb)
    {
        var concurrencyColumn = model.Columns.AsSpan().ToArray().FirstOrDefault(c => c.IsConcurrencyToken);
        if (concurrencyColumn is null) return;
        sb.AppendLine($"        entity.{concurrencyColumn.PropertyName}++;");
    }

    private static void GenerateSetIdBody(TableModel model, StringBuilder sb)
    {
        var pkCol = model.Columns.AsSpan().ToArray().FirstOrDefault(c => c.IsPrimaryKey);
        if (pkCol is null || !pkCol.IsAutoIncrement)
        {
            sb.AppendLine("        // 仅自增 int/long 主键需要数据库 ID 回填");
            return;
        }
        // 生成的代码: entity.Id = id; 或 entity.UserId = (int)id;
        string cast = pkCol.ClrTypeName switch
        {
            _ when pkCol.ClrTypeName.EndsWith("Int32") || pkCol.ClrTypeName.EndsWith("int") => "(int)",
            _ when pkCol.ClrTypeName.EndsWith("Int64") || pkCol.ClrTypeName.EndsWith("long") => "",
            _ => "(long)" // 默认转为 long 再写入
        };
        sb.AppendLine($"        entity.{pkCol.PropertyName} = {cast}id;");
    }

    internal static string BuildInsertSql(TableModel model)
        => BuildInsertSql(model, null);

    internal static string BuildInsertSql(TableModel model, SqlGenerationDialect? dialect)
    {
        string Quote(string value) => dialect is null
            ? value
            : SqlGeneration.QuoteIdentifier(value, dialect.Value);
        ColumnModel[] columns = model.Columns.AsSpan().ToArray()
            .Where(static column => column.IsInsertable).ToArray();
        var parameterNames = columns.Select((_, index) => $"@p{index}");
        return $"INSERT INTO {Quote(model.TableName)} " +
            $"({string.Join(", ", columns.Select(column => Quote(column.ColumnName)))}) " +
            $"VALUES ({string.Join(", ", parameterNames)})";
    }

    internal static string BuildUpdateSql(TableModel model)
    {
        ColumnModel[] columns = model.Columns.AsSpan().ToArray();
        ColumnModel[] primaryKeys = columns.Where(static column => column.IsPrimaryKey).ToArray();
        ColumnModel[] setColumns = columns.Where(static column =>
            !column.IsPrimaryKey && !column.IsConcurrencyToken &&
            !column.IsTimestamp && column.ComputedExpression is null).ToArray();
        ColumnModel? concurrency = columns.FirstOrDefault(static column => column.IsConcurrencyToken);
        int parameterIndex = 0;
        var sets = setColumns.Select(column =>
            $"{column.ColumnName}=@p{parameterIndex++}").ToList();
        if (concurrency is not null)
            sets.Add($"{concurrency.ColumnName}={concurrency.ColumnName} + 1");
        if (sets.Count == 0)
            return string.Empty;

        var conditions = primaryKeys.Select(column =>
            $"{column.ColumnName}=@p{parameterIndex++}").ToList();
        if (concurrency is not null)
            conditions.Add($"{concurrency.ColumnName}=@p{parameterIndex}");
        return $"UPDATE {model.TableName} SET {string.Join(", ", sets)} " +
            $"WHERE {string.Join(" AND ", conditions)}";
    }

    internal static string BuildUpdateSql(TableModel model, SqlGenerationDialect? dialect)
    {
        string Quote(string value) => dialect is null
            ? value
            : SqlGeneration.QuoteIdentifier(value, dialect.Value);
        ColumnModel[] columns = model.Columns.AsSpan().ToArray();
        ColumnModel[] primaryKeys = columns.Where(static column => column.IsPrimaryKey).ToArray();
        ColumnModel[] setColumns = columns.Where(static column =>
            !column.IsPrimaryKey && !column.IsConcurrencyToken &&
            !column.IsTimestamp && column.ComputedExpression is null).ToArray();
        ColumnModel? concurrency = columns.FirstOrDefault(static column => column.IsConcurrencyToken);
        int parameterIndex = 0;
        var sets = setColumns.Select(column =>
            $"{Quote(column.ColumnName)} = @p{parameterIndex++}").ToList();
        if (concurrency is not null)
            sets.Add($"{Quote(concurrency.ColumnName)} = {Quote(concurrency.ColumnName)} + 1");
        if (sets.Count == 0)
            return string.Empty;

        var conditions = primaryKeys.Select(column =>
            $"{Quote(column.ColumnName)} = @p{parameterIndex++}").ToList();
        if (concurrency is not null)
            conditions.Add($"{Quote(concurrency.ColumnName)} = @p{parameterIndex}");
        return $"UPDATE {Quote(model.TableName)} SET {string.Join(", ", sets)} " +
            $"WHERE {string.Join(" AND ", conditions)}";
    }

    internal static string BuildDeleteSql(TableModel model)
        => BuildDeleteSql(model, null);

    internal static string BuildDeleteSql(TableModel model, SqlGenerationDialect? dialect)
    {
        string Quote(string value) => dialect is null
            ? value
            : SqlGeneration.QuoteIdentifier(value, dialect.Value);
        ColumnModel[] primaryKeys = model.Columns.AsSpan().ToArray()
            .Where(static column => column.IsPrimaryKey).ToArray();
        var conditions = primaryKeys.Select((column, index) =>
            $"{Quote(column.ColumnName)} = @p{index}");
        return $"DELETE FROM {Quote(model.TableName)} WHERE " +
            string.Join(" AND ", conditions);
    }

    internal static string BuildInsertReturningSql(TableModel model)
        => BuildInsertReturningSql(model, null);

    internal static string BuildInsertReturningSql(
        TableModel model, SqlGenerationDialect? dialect)
    {
        string Quote(string value) => dialect is null
            ? value
            : SqlGeneration.QuoteIdentifier(value, dialect.Value);
        return BuildInsertSql(model, dialect) + " RETURNING " +
            string.Join(", ", model.Columns.AsSpan().ToArray()
                .Select(column => Quote(column.ColumnName)));
    }

    private static void GenerateBindInsertBody(TableModel model, StringBuilder sb)
    {
        int pi = 0;
        foreach (var col in model.Columns.AsSpan())
        {
            if (!col.IsInsertable) continue;
            string valueExpr = GetParameterValueExpression(col);
            sb.AppendLine($"        {{ var p = cmd.CreateParameter(); p.ParameterName = \"@p{pi}\"; p.Value = {valueExpr}; cmd.Parameters.Add(p); }}");
            pi++;
        }
    }

    private static void GenerateBindUpdateBody(TableModel model, StringBuilder sb)
    {
        var cols = model.Columns.AsSpan().ToArray();
        var setCols = cols.Where(c => !c.IsPrimaryKey && !c.IsConcurrencyToken
            && !c.IsTimestamp && c.ComputedExpression is null).ToArray();
        var pkCols = cols.Where(c => c.IsPrimaryKey).ToArray();
        var cc = cols.FirstOrDefault(c => c.IsConcurrencyToken);

        int pi = 0;
        foreach (var col in setCols)
        {
            string valueExpr = GetParameterValueExpression(col);
            sb.AppendLine($"        {{ var p = cmd.CreateParameter(); p.ParameterName = \"@p{pi++}\"; p.Value = {valueExpr}; cmd.Parameters.Add(p); }}");
        }
        foreach (var col in pkCols)
        {
            string valueExpr = GetParameterValueExpression(col);
            sb.AppendLine($"        {{ var p = cmd.CreateParameter(); p.ParameterName = \"@p{pi++}\"; p.Value = {valueExpr}; cmd.Parameters.Add(p); }}");
        }
        if (cc is not null)
        {
            sb.AppendLine($"        {{ var p = cmd.CreateParameter(); p.ParameterName = \"@p{pi}\"; p.Value = entity.{cc.PropertyName}; cmd.Parameters.Add(p); }}");
        }
    }

    private static string GetParameterValueExpression(ColumnModel col)
    {
        if (IsObjectOwnedJson(col))
            return col.IsNullable
                ? $"entity.{col.PropertyName} is null ? global::System.DBNull.Value : (object)global::System.Text.Json.JsonSerializer.Serialize(entity.{col.PropertyName}, JsonTypeInfo_{col.PropertyName})"
                : $"(object)global::System.Text.Json.JsonSerializer.Serialize(entity.{col.PropertyName}, JsonTypeInfo_{col.PropertyName})";

        string valueExpression = col.ConverterTypeName is null
            ? $"entity.{col.PropertyName}"
            : $"(({GetConverterInterfaceType(col)})new {col.ConverterTypeName}()).ToProvider(entity.{col.PropertyName})";
        return col.IsNullable
            ? $"entity.{col.PropertyName} is null ? global::System.DBNull.Value : (object){valueExpression}"
            : $"(object){valueExpression}";
    }

    private static string GetConverterInterfaceType(ColumnModel column)
        => $"global::PalORM.IValueConverter<{column.ClrTypeName}, {column.ProviderClrTypeName}>";

    private static bool IsObjectOwnedJson(ColumnModel column)
        => column.IsOwnedJson
            && column.ClrTypeName is not "string" and not "global::System.String";
}
