using System.Text;

namespace PalORM.SourceGen;

internal static class CommandFactoryEmitter
{
    internal static string Generate(TableModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace PalORM.Generated;");
        sb.AppendLine();
        sb.AppendLine(GeneratedCodeMetadata.GeneratedCodeAttribute);
        sb.AppendLine($"internal static class CommandFactory_{model.GeneratedTypeSuffix}");
        sb.AppendLine("{");

        // v4.0 性能优化 A：Converter 单例对齐 RowFactory 模式。
        // v3.1 RowFactoryEmitter 已用 static readonly Converter 字段，CommandFactory 仍每次 new——不对称。
        // Bind 路径（Insert/Update/Upsert/Delete）被高频调用：百万行 BulkInsert 含 2 Converter 列省 ~200 万 Gen0 分配。
        int converterCount = 0;
        foreach (var col in model.Columns)
        {
            if (col.ConverterTypeName is null) continue;
            sb.AppendLine($"    private static readonly global::PalORM.IValueConverter<{col.ClrTypeName}, {col.ProviderClrTypeName}> _conv_{col.PropertyName} = new {col.ConverterTypeName}();");
            converterCount++;
        }
        if (converterCount > 0)
            sb.AppendLine();

        foreach (var column in model.Columns.AsSpan())
        {
            if (!IsObjectOwnedJson(column)) continue;
            // JsonSerializerContext（OwnedJson 用的 context.Default）只有非泛型 GetTypeInfo(Type)——
            // 泛型 GetTypeInfo<T>() 在 JsonSerializerOptions 上（不在 Context 上），此处保持强转形态。
            sb.AppendLine($"    internal static readonly global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<{column.ClrTypeName}> JsonTypeInfo_{column.PropertyName} = (global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<{column.ClrTypeName}>)({column.OwnedJsonContextTypeName}.Default.GetTypeInfo(typeof({column.ClrTypeName})) ?? throw new global::System.InvalidOperationException(\"OwnedJson type metadata was not generated.\"));");
        }
        sb.AppendLine();
        sb.AppendLine($"    /// <summary>绑定实体属性到 INSERT 参数（支持批量 offset 偏移）。</summary>");
        sb.AppendLine($"    internal static void BindInsertToBatch(global::System.Data.Common.DbCommand cmd, {model.EntityTypeName} entity, int paramOffset)");
        sb.AppendLine("    {");
        GenerateBindInsertBody(model, sb);
        sb.AppendLine("    }");
        sb.AppendLine();
        // v4.6：参数复用路径 -- 接收预分配的 DbParameter[]，只改 Value，不 CreateParameter/Add
        sb.AppendLine($"    /// <summary>仅设置预分配参数的 Value（跨批复用路径，零 CreateParameter 分配）。</summary>");
        sb.AppendLine($"    internal static void BindInsertValues(global::System.Data.Common.DbParameter[] parameters, {model.EntityTypeName} entity, int paramOffset)");
        sb.AppendLine("    {");
        GenerateBindValuesBody(model, sb);
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine($"    /// <summary>绑定实体属性到 UPSERT 参数，包含主键。</summary>");
        sb.AppendLine($"    internal static void BindUpsert(global::System.Data.Common.DbCommand cmd, {model.EntityTypeName} entity)");
        sb.AppendLine("    {");
        GenerateBindUpsertBody(model, sb);
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine($"    /// <summary>绑定实体属性到 UPDATE 参数。</summary>");
        sb.AppendLine($"    internal static void BindUpdate(global::System.Data.Common.DbCommand cmd, {model.EntityTypeName} entity)");
        sb.AppendLine("    {");
        GenerateBindUpdateBody(model, sb);
        sb.AppendLine("    }");
        sb.AppendLine();
        // v5.6：参数复用路径——接收预分配的 DbParameter[]，只改 Value，不 CreateParameter/Add。
        // 与 BindInsertValues 同一机制。消费点是 BulkUpdateBatchAsync 的单语句批量 UPDATE：
        // 其 probe 命令原先逐行 BindUpdate 建参数（40000 行 × 4 列 = 16 万次创建），
        // 而目标参数池本身没问题——真库实测该路径 2671 B/行（PG），远超 MySQL 多值 INSERT 的 359。
        // paramOffset 供扁平池的按行基址使用（池长 batchLen × paramsPerRow）。
        sb.AppendLine($"    /// <summary>仅设置预分配 UPDATE 参数的 Value（批量 UPDATE 参数池路径，零 CreateParameter 分配）。</summary>");
        sb.AppendLine($"    internal static void BindUpdateValues(global::System.Data.Common.DbParameter[] parameters, {model.EntityTypeName} entity, int paramOffset)");
        sb.AppendLine("    {");
        GenerateBindUpdateValuesBody(model, sb);
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine($"    /// <summary>绑定主键到 DELETE 参数。</summary>");
        sb.AppendLine($"    internal static void BindDelete(global::System.Data.Common.DbCommand cmd, object key)");
        sb.AppendLine("    {");
        GenerateBindDeleteBody(model, sb);
        sb.AppendLine("    }");
        sb.AppendLine();
        // SetId: 编译时安全设置自增主键（零反射，替代 MySQL LAST_INSERT_ID 后 Type.GetProperties()）
        sb.AppendLine($"    internal static void SetId({model.EntityTypeName} entity, long id)");
        sb.AppendLine("    {");
        GenerateSetIdBody(model, sb);
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine($"    internal static void IncrementVersion({model.EntityTypeName} entity)");
        sb.AppendLine("    {");
        GenerateIncrementVersionBody(model, sb);
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine($"    internal static bool HasDefaultKey({model.EntityTypeName} entity)");
        sb.AppendLine("    {");
        GenerateHasDefaultKeyBody(model, sb);
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void GenerateBindDeleteBody(TableModel model, StringBuilder sb)
    {
        var pkCols = model.Columns.AsSpan().ToArray().Where(c => c.IsPrimaryKey).ToArray();
        int pi = 0;
        foreach (var col in pkCols)
        {
            // ITM-587/627：整数主键用 Convert.ToXxx(key) 而非直接 cast：
            // 调用方可能传 int（如 BenchmarkDotNet 的 NextId()）、byte 等装箱为 object，
            // 直接 (long)key 在 key 是 int 时抛 InvalidCastException。Convert 在装箱类型间
            // 自动转换，代价仅几 ns。Converter 列同样归一化（627——先归一到 CLR 侧类型再交
            // ToProvider）；非基元类型保持类型化 cast（默认 key 对 Converter 列不编译）。
            string castExpr = NormalizeClrType(col.ClrTypeName) switch
            {
                "long" or "global::System.Int64" => "global::System.Convert.ToInt64(key)",
                "int" or "global::System.Int32" => "global::System.Convert.ToInt32(key)",
                "short" or "global::System.Int16" => "global::System.Convert.ToInt16(key)",
                "byte" or "global::System.Byte" => "global::System.Convert.ToByte(key)",
                // string/Guid 保持精确 cast——语义不同（不接受 int→string 隐式转换）
                "string" or "global::System.String" => "((string)key)",
                "global::System.Guid" => "((global::System.Guid)key)",
                // ITM-743(r20)：decimal/DateTime 等 IConvertible 主键用 Convert.ChangeType 归一——
                // 此前原样装箱（(object)key）与 int/long 的归一处理不对称，异型 key 靠驱动隐式转换。
                // 同型装箱值 ChangeType 直返，行为不变。Converter 列保持原类型化 cast（先归一到 CLR 侧）。
                _ when col.ConverterTypeName is not null => $"({col.ClrTypeName})key",
                _ => $"global::System.Convert.ChangeType(key, typeof({col.ClrTypeName}), global::System.Globalization.CultureInfo.InvariantCulture)"
            };
            string providerValueExpr = col.ConverterTypeName is null
                ? castExpr
                : $"_conv_{col.PropertyName}.ToProvider({castExpr})";
            string valueExpr = col.IsNullable
                ? $"{castExpr} is null ? global::System.DBNull.Value : (object){providerValueExpr}"
                : $"(object){providerValueExpr}";
            sb.AppendLine($"        {{ var p = cmd.CreateParameter(); p.ParameterName = \"@p{pi}\"; {DbTypeHint(col)}p.Value = {valueExpr}; cmd.Parameters.Add(p); }}");
            pi++;
        }
    }

    private static void GenerateHasDefaultKeyBody(TableModel model, StringBuilder sb)
    {
        var pkColumn = model.Columns.AsSpan().ToArray().FirstOrDefault(c => c.IsPrimaryKey);
        if (pkColumn is null)
        {
            sb.AppendLine("        return true;");
            return;
        }
        sb.AppendLine($"        return global::System.Collections.Generic.EqualityComparer<{pkColumn.ClrTypeName}>.Default.Equals(entity.{pkColumn.EscapedPropertyName}, default);");
    }

    private static void GenerateIncrementVersionBody(TableModel model, StringBuilder sb)
    {
        var concurrencyColumn = model.Columns.AsSpan().ToArray().FirstOrDefault(c => c.IsConcurrencyToken);
        if (concurrencyColumn is null) return;
        sb.AppendLine($"        entity.{concurrencyColumn.EscapedPropertyName}++;");
    }

    private static void GenerateSetIdBody(TableModel model, StringBuilder sb)
    {
        var pkCol = model.Columns.AsSpan().ToArray().FirstOrDefault(c => c.IsPrimaryKey);
        if (pkCol is null || !pkCol.IsAutoIncrement)
        {
            sb.AppendLine("        // 仅自增 int/long 主键需要数据库 ID 回填");
            return;
        }
        // 生成的代码: entity.Id = id; 或 entity.UserId = (int)id;（IsAutoIncrement 已限定 int/long）
        string cast = NormalizeClrType(pkCol.ClrTypeName) switch
        {
            "int" or "global::System.Int32" => "(int)",
            "long" or "global::System.Int64" => "",
            _ => "(long)" // 默认转为 long 再写入
        };
        sb.AppendLine($"        entity.{pkCol.EscapedPropertyName} = {cast}id;");
    }

    /// <summary>去除可空标注（string? → string），供主键类型精确匹配——EndsWith 匹配
    /// 会误伤 uint/ulong（ITM-505）。主键不会是可空引用类型，此处仅剥可能的尾随 '?'。</summary>
    private static string NormalizeClrType(string clrTypeName)
        => clrTypeName.EndsWith("?", System.StringComparison.Ordinal)
            ? clrTypeName.Substring(0, clrTypeName.Length - 1)
            : clrTypeName;

    // 评审 2026-09-02 收敛：无方言（Quote 恒等）重载已删除——方言参数必填，方言 SQL 是
    // 唯一真源。此前 legacy 集合发射进注册表后被运行时 GetCommandSqls 拒绝（ITM-684），
    // 纯属"标识符未经引用转义的死载荷"，且是关键字列名静默产出非法 SQL 的隐患面。

    internal static string BuildInsertSql(TableModel model, SqlGenerationDialect dialect)
    {
        string Quote(string value) => SqlGeneration.QuoteIdentifier(value, dialect);
        ColumnModel[] columns = model.Columns.AsSpan().ToArray()
            .Where(static column => column.IsInsertable).ToArray();
        var parameterNames = columns.Select((_, index) => $"@p{index}");
        return $"INSERT INTO {Quote(model.TableName)} " +
            $"({string.Join(", ", columns.Select(column => Quote(column.ColumnName)))}) " +
            $"VALUES ({string.Join(", ", parameterNames)})";
    }

    // ITM-552：UPDATE 的 SET 列谓词——BuildUpdateSql（生成 SQL）与 GenerateBindUpdateBody（绑定参数）
    // 曾各自内联复制此条件，二者必须逐字一致否则参数序与占位符错位。提取为单一真源防漂移。
    // ITM-642：RegistryEmitter 发射 CrudColumns.Update 亦消费本谓词——运行时 BulkUpdateBatchAsync
    // 直接读元数据列集，与生成 SQL/绑定序三处同源。
    internal static bool IsUpdatableColumn(ColumnModel col)
        => !col.IsPrimaryKey && !col.IsConcurrencyToken
            && !col.IsTimestamp && col.ComputedExpression is null;

    internal static string BuildUpdateSql(TableModel model, SqlGenerationDialect dialect)
    {
        string Quote(string value) => SqlGeneration.QuoteIdentifier(value, dialect);
        ColumnModel[] columns = model.Columns.AsSpan().ToArray();
        ColumnModel[] primaryKeys = columns.Where(static column => column.IsPrimaryKey).ToArray();
        ColumnModel[] setColumns = columns.Where(static column =>
            IsUpdatableColumn(column)).ToArray();
        ColumnModel? concurrency = columns.FirstOrDefault(static column => column.IsConcurrencyToken);
        int parameterIndex = 0;
        var sets = setColumns.Select(column =>
            $"{Quote(column.ColumnName)} = @p{parameterIndex++}").ToList();
        if (concurrency is not null)
            sets.Add($"{Quote(concurrency.ColumnName)} = {Quote(concurrency.ColumnName)} + 1");
        if (sets.Count == 0)
            return string.Empty;

        var conditions = primaryKeys.Select(column =>
            $"{Quote(column.ColumnName)} = @p{parameterIndex++}").ToList();
        if (concurrency is not null)
            conditions.Add($"{Quote(concurrency.ColumnName)} = @p{parameterIndex}");
        return $"UPDATE {Quote(model.TableName)} SET {string.Join(", ", sets)} " +
            $"WHERE {string.Join(" AND ", conditions)}";
    }

    internal static string BuildDeleteSql(TableModel model, SqlGenerationDialect dialect)
    {
        string Quote(string value) => SqlGeneration.QuoteIdentifier(value, dialect);
        ColumnModel[] primaryKeys = model.Columns.AsSpan().ToArray()
            .Where(static column => column.IsPrimaryKey).ToArray();
        var conditions = primaryKeys.Select((column, index) =>
            $"{Quote(column.ColumnName)} = @p{index}");
        return $"DELETE FROM {Quote(model.TableName)} WHERE " +
            string.Join(" AND ", conditions);
    }

    internal static string BuildInsertReturningSql(
        TableModel model, SqlGenerationDialect dialect)
    {
        // MySQL 无 RETURNING：生成空串而非无效 SQL——绕过 SupportsReturningClause 守卫的
        // 误用会以"空 CommandText"明确失败，不会把非法语句发给服务器。
        if (dialect == SqlGenerationDialect.MySql)
            return string.Empty;
        string Quote(string value) => SqlGeneration.QuoteIdentifier(value, dialect);
        // v5.7 收窄：满足 SupportsKeyOnlyReturning 时只回主键——整行物化等价于
        // 返回调用方实体+回填 ID（判定条件见该方法文档），省整行网络与物化。
        if (SupportsKeyOnlyReturning(model))
        {
            ColumnModel pk = model.Columns.AsSpan().ToArray()
                .First(static c => c.IsPrimaryKey);
            return BuildInsertSql(model, dialect) + " RETURNING " + Quote(pk.ColumnName);
        }
        return BuildInsertSql(model, dialect) + " RETURNING " +
            string.Join(", ", model.Columns.AsSpan().ToArray()
                .Select(column => Quote(column.ColumnName)));
    }

    /// <summary>「RETURNING 只回主键」的静态判定——保守条件，全部满足才收窄：
    /// ① 恰一个主键且自增（唯一需要从 DB 取回的值）；
    /// ② 其余全部列 IsInsertable（无 IgnoreOnInsert——该类列不进 INSERT，
    ///   DB 默认值与调用方实体值**可能不同**，物化返回才是真源；无 Computed/Timestamp——
    ///   DB 计算值必然与插入值不同）；
    /// ③ 无转换器列、无 OwnedJson——值经 f→g 往返不保证恒等。
    /// 任一不满足 → 保持整行 RETURNING + 物化（既有契约）。</summary>
    internal static bool SupportsKeyOnlyReturning(TableModel model)
    {
        var columns = model.Columns.AsSpan().ToArray();
        ColumnModel[] primaryKeys = [.. columns.Where(static c => c.IsPrimaryKey)];
        if (primaryKeys.Length != 1 || !primaryKeys[0].IsAutoIncrement)
            return false;
        return columns.All(static c =>
            (c.IsInsertable && c.ConverterTypeName is null && !c.IsOwnedJson)
            || (c.IsPrimaryKey && c.IsAutoIncrement));
    }

    // ── Upsert SQL 预构建（v4.1 性能优化：消除运行时 LINQ + string.Join 拼接）──
    // 运行时 UpsertWithReturningAsync / UpsertWithMySqlAsync 直接取 const，零分配。

    internal static string BuildUpsertReturningSql(
        TableModel model, SqlGenerationDialect dialect)
    {
        // MySQL 无 RETURNING：空串
        if (dialect == SqlGenerationDialect.MySql)
            return string.Empty;

        string Quote(string value) => SqlGeneration.QuoteIdentifier(value, dialect);

        ColumnModel[] upsertColumns = model.Columns.AsSpan().ToArray()
            .Where(static column => column.IsUpsertable).ToArray();
        ColumnModel[] pkCols = upsertColumns.Where(static c => c.IsPrimaryKey).ToArray();
        if (pkCols.Length == 0)
            return string.Empty;

        string pkColumnName = pkCols[0].ColumnName;
        string[] updateColumns = upsertColumns
            .Where(column => !string.Equals(column.ColumnName, pkColumnName, StringComparison.Ordinal))
            .Select(column => Quote(column.ColumnName))
            .ToArray();

        string conflictAction = updateColumns.Length == 0
            ? "DO NOTHING"
            : "DO UPDATE SET " + string.Join(", ", updateColumns.Select(column =>
                $"{column} = excluded.{column}"));

        string columnList = string.Join(", ", upsertColumns.Select(c => Quote(c.ColumnName)));
        string valueList = string.Join(", ",
            Enumerable.Range(0, upsertColumns.Length).Select(static index => $"@p{index}"));
        string returningList = string.Join(", ", model.Columns.AsSpan().ToArray()
            .Select(column => Quote(column.ColumnName)));

        return $"INSERT INTO {Quote(model.TableName)} ({columnList}) " +
            $"VALUES ({valueList}) ON CONFLICT " +
            $"({Quote(pkColumnName)}) {conflictAction} " +
            $"RETURNING {returningList}";
    }

    internal static string BuildUpsertMySqlSql(
        TableModel model, SqlGenerationDialect dialect)
    {
        string Quote(string value) => SqlGeneration.QuoteIdentifier(value, dialect);

        ColumnModel[] upsertColumns = model.Columns.AsSpan().ToArray()
            .Where(static column => column.IsUpsertable).ToArray();
        ColumnModel[] pkCols = upsertColumns.Where(static c => c.IsPrimaryKey).ToArray();
        if (pkCols.Length == 0)
            return string.Empty;

        string pkColumnName = pkCols[0].ColumnName;
        string[] updateColumns = upsertColumns
            .Where(column => !string.Equals(column.ColumnName, pkColumnName, StringComparison.Ordinal))
            .Select(column => Quote(column.ColumnName))
            .ToArray();

        string columnList = string.Join(", ", upsertColumns.Select(c => Quote(c.ColumnName)));
        string valueList = string.Join(", ",
            Enumerable.Range(0, upsertColumns.Length).Select(static index => $"@p{index}"));

        // ON DUPLICATE KEY UPDATE 赋值项，对齐旧运行时语义（DataSession.BuildMySqlUpsertSetClause）：
        // ITM-608 修复——原 `col == Quote(pk)` 比较在 updateColumns（已排除 PK 再 Quote）上恒 false，
        // LAST_INSERT_ID 赋值与 "; SELECT LAST_INSERT_ID()" 后缀全部丢失 → 自增主键 upsert 后不回填。
        // ① 非 PK 列 VALUES(col) 回写；② 自增 PK 追加 LAST_INSERT_ID(pk)（更新已有行时
        // SELECT LAST_INSERT_ID() 返回该行 PK）；③ 空更新列回写 PK 保持 no-op upsert 语义
        // （MySQL 无 DO NOTHING，等价形态 = pk=VALUES(pk) / pk=LAST_INSERT_ID(pk)）。
        bool isAutoIncrement = pkCols[0].IsAutoIncrement;
        string quotedPk = Quote(pkCols[0].ColumnName);
        List<string> assignments = updateColumns
            .Select(static col => $"{col} = VALUES({col})")
            .ToList();
        if (isAutoIncrement || updateColumns.Length == 0)
            assignments.Add(isAutoIncrement
                ? $"{quotedPk} = LAST_INSERT_ID({quotedPk})"
                : $"{quotedPk} = VALUES({quotedPk})");

        string sql = $"INSERT INTO {Quote(model.TableName)} ({columnList}) VALUES ({valueList})" +
            $" ON DUPLICATE KEY UPDATE {string.Join(", ", assignments)}";
        // 仅自增键实体回填：消费端（UpsertWithMySqlAsync）只对有 SetIdDelegates 的实体走
        // ExecuteScalarAsync，非自增键执行 ExecuteNonQueryAsync——后缀对它是多余结果集。
        return isAutoIncrement ? $"{sql}; SELECT LAST_INSERT_ID()" : sql;
    }

    private static void GenerateBindInsertBody(TableModel model, StringBuilder sb)
        => GenerateBindBody(model, sb, static column => column.IsInsertable, withOffset: true);

    private static void GenerateBindUpsertBody(TableModel model, StringBuilder sb)
        => GenerateBindBody(model, sb, static column => column.IsUpsertable, withOffset: false);

    /// <summary>共享 Bind 循环。v4.1：withOffset=true 时参数名用 @p{paramOffset+pi}（批量直绑），false 时用 @p{pi}（单行）。
    /// ITM-764(r21)：不再向参数写 SourceColumn——掩码载体已迁移至注册表
    /// SensitiveColumnMasks + QueryContext.SensitiveParameterMasks（Set 路径经 QueryBuilder 记录），
    /// 不挪用 ADO.NET DataAdapter 的列映射标准属性。</summary>
    private static void GenerateBindBody(TableModel model, StringBuilder sb, Func<ColumnModel, bool> predicate, bool withOffset)
    {
        int pi = 0;
        foreach (var col in model.Columns.AsSpan())
        {
            if (!predicate(col)) continue;
            string valueExpr = GetParameterValueExpression(col);
            // withOffset=true 时生成 $\"@p{paramOffset + N}\"（插值表达式），false 时生成 \"@pN\"（字面量）
            string paramName = withOffset ? $"global::PalORM.ParameterNameCache.GetName(paramOffset + {pi})" : $"\"@p{pi}\"";
            sb.AppendLine($"        {{ var p = cmd.CreateParameter(); p.ParameterName = {paramName}; {DbTypeHint(col)}p.Value = {valueExpr}; cmd.Parameters.Add(p); }}");
            pi++;
        }
    }


    /// <summary>v4.6：仅设置预分配参数的 Value（无 CreateParameter/Add/ParameterName），用于跨批参数复用。</summary>
    private static void GenerateBindValuesBody(TableModel model, StringBuilder sb)
    {
        int pi = 0;
        foreach (var col in model.Columns.AsSpan())
        {
            if (!col.IsInsertable) continue;
            string valueExpr = GetParameterValueExpression(col);
            if (IsBinaryColumn(col))
                sb.AppendLine($"        parameters[paramOffset + {pi}].DbType = global::System.Data.DbType.Binary;");
            sb.AppendLine($"        parameters[paramOffset + {pi}].Value = {valueExpr};");
            pi++;
        }
    }

    // v4.1：MySQL INSERT + SELECT LAST_INSERT_ID() 预构建，消除运行时 string 拼接
    internal static string BuildInsertWithLastInsertIdSql(
        TableModel model, SqlGenerationDialect dialect)
        => BuildInsertSql(model, dialect) + "; SELECT LAST_INSERT_ID()";

    private static void GenerateBindUpdateBody(TableModel model, StringBuilder sb)
    {
        var cols = model.Columns.AsSpan().ToArray();
        var setCols = cols.Where(c => IsUpdatableColumn(c)).ToArray();
        var pkCols = cols.Where(c => c.IsPrimaryKey).ToArray();
        var cc = cols.FirstOrDefault(c => c.IsConcurrencyToken);

        int pi = 0;
        foreach (var col in setCols)
        {
            string valueExpr = GetParameterValueExpression(col);
            sb.AppendLine($"        {{ var p = cmd.CreateParameter(); p.ParameterName = \"@p{pi++}\"; {DbTypeHint(col)}p.Value = {valueExpr}; cmd.Parameters.Add(p); }}");
        }
        foreach (var col in pkCols)
        {
            string valueExpr = GetParameterValueExpression(col);
            sb.AppendLine($"        {{ var p = cmd.CreateParameter(); p.ParameterName = \"@p{pi++}\"; {DbTypeHint(col)}p.Value = {valueExpr}; cmd.Parameters.Add(p); }}");
        }
        if (cc is not null)
        {
            sb.AppendLine($"        {{ var p = cmd.CreateParameter(); p.ParameterName = \"@p{pi}\"; p.Value = entity.{cc.EscapedPropertyName}; cmd.Parameters.Add(p); }}");
        }
    }

    /// <summary>BindUpdateValues 的发射体——列序与 <see cref="GenerateBindUpdateBody"/> 逐字一致
    /// （SET 列 → 主键 → 并发令牌），否则参数序与 <c>BatchUpdateSqlBuilder</c> 的占位符错位。
    /// 差异仅在「写 Value」与「建参数+Add」：目标池由调用方预分配。</summary>
    private static void GenerateBindUpdateValuesBody(TableModel model, StringBuilder sb)
    {
        var cols = model.Columns.AsSpan().ToArray();
        var setCols = cols.Where(c => IsUpdatableColumn(c)).ToArray();
        var pkCols = cols.Where(c => c.IsPrimaryKey).ToArray();
        var cc = cols.FirstOrDefault(c => c.IsConcurrencyToken);

        int pi = 0;
        foreach (var col in setCols)
        {
            string valueExpr = GetParameterValueExpression(col);
            if (IsBinaryColumn(col))
                sb.AppendLine($"        parameters[paramOffset + {pi}].DbType = global::System.Data.DbType.Binary;");
            sb.AppendLine($"        parameters[paramOffset + {pi++}].Value = {valueExpr};");
        }
        foreach (var col in pkCols)
        {
            string valueExpr = GetParameterValueExpression(col);
            if (IsBinaryColumn(col))
                sb.AppendLine($"        parameters[paramOffset + {pi}].DbType = global::System.Data.DbType.Binary;");
            sb.AppendLine($"        parameters[paramOffset + {pi++}].Value = {valueExpr};");
        }
        if (cc is not null)
        {
            sb.AppendLine($"        parameters[paramOffset + {pi}].Value = entity.{cc.EscapedPropertyName};");
        }
    }

    /// <summary>byte[] provider 列的参数绑定显式化：DbType.Binary 在生成物中可见——
    /// PG COPY 经 NpgsqlParameter.DbType → NpgsqlDbType.Bytea（不再依赖驱动从 Value 的
    /// 运行时推断），MySQL/SQLite 同步获得确定性二进制分派。</summary>
    private static string DbTypeHint(ColumnModel col)
        => IsBinaryColumn(col) ? "p.DbType = global::System.Data.DbType.Binary; " : "";

    private static bool IsBinaryColumn(ColumnModel col)
        => col.ProviderClrTypeName is "byte[]" or "global::System.Byte[]";

    private static string GetParameterValueExpression(ColumnModel col)
    {
        if (IsObjectOwnedJson(col))
            return col.IsNullable
                ? $"entity.{col.EscapedPropertyName} is null ? global::System.DBNull.Value : (object)global::System.Text.Json.JsonSerializer.Serialize(entity.{col.EscapedPropertyName}, JsonTypeInfo_{col.PropertyName})"
                : $"(object)global::System.Text.Json.JsonSerializer.Serialize(entity.{col.EscapedPropertyName}, JsonTypeInfo_{col.PropertyName})";

        string valueExpression = col.ConverterTypeName is null
            ? $"entity.{col.EscapedPropertyName}"
            : $"_conv_{col.PropertyName}.ToProvider(entity.{col.EscapedPropertyName})";
        return col.IsNullable
            ? $"entity.{col.EscapedPropertyName} is null ? global::System.DBNull.Value : (object){valueExpression}"
            : $"(object){valueExpression}";
    }

    private static bool IsObjectOwnedJson(ColumnModel column)
        => column.IsOwnedJson
            && column.ClrTypeName is not "string" and not "global::System.String";
}
