using System.Text;
using Microsoft.CodeAnalysis.CSharp;

namespace PalORM.SourceGen;

/// <summary>迁移 DDL 代码生成器——为 [Table] 类生成 CREATE TABLE/INDEX/FOREIGN KEY 语句。</summary>
internal static class MigrationEmitter
{
    internal static string Generate(TableModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace PalORM.Generated;");
        sb.AppendLine();
        sb.AppendLine($"internal static class Migration_{model.GeneratedTypeSuffix}");
        sb.AppendLine("{");

        string legacy = BuildCreateTable(model);
        string sqlite = BuildCreateTable(model, SqlGenerationDialect.Sqlite);
        string postgreSql = BuildCreateTable(model, SqlGenerationDialect.PostgreSql);
        string mySql = BuildCreateTable(model, SqlGenerationDialect.MySql);
        sb.AppendLine($"    internal const string CreateTable = {ToCSharpLiteral(legacy)};");
        sb.AppendLine($"    internal const string CreateTableSqlite = {ToCSharpLiteral(sqlite)};");
        sb.AppendLine($"    internal const string CreateTablePostgreSql = {ToCSharpLiteral(postgreSql)};");
        sb.AppendLine($"    internal const string CreateTableMySql = {ToCSharpLiteral(mySql)};");
        sb.AppendLine();

        foreach (IndexModel index in model.Indexes.AsSpan())
        {
            string unique = index.Unique ? "UNIQUE " : "";
            string columns = string.Join(", ", index.Columns.AsSpan().ToArray()
                .Select(static column => SqlGeneration.QuoteIdentifier(
                    column, SqlGenerationDialect.Sqlite)));
            string sql = $"CREATE {unique}INDEX IF NOT EXISTS " +
                $"{SqlGeneration.QuoteIdentifier(index.Name, SqlGenerationDialect.Sqlite)} ON " +
                $"{SqlGeneration.QuoteIdentifier(model.TableName, SqlGenerationDialect.Sqlite)} ({columns})";
            sb.AppendLine($"    internal const string CreateIndex_{index.Name} = {ToCSharpLiteral(sql)};");
        }

        foreach (ForeignKeyModel foreignKey in model.ForeignKeys.AsSpan())
        {
            string onDelete = foreignKey.OnDelete switch
            {
                1 => " ON DELETE CASCADE",
                2 => " ON DELETE SET NULL",
                3 => " ON DELETE RESTRICT",
                _ => ""
            };
            string constraintName = $"FK_{model.TableName}_{foreignKey.PropertyName}";
            string sql = $"ALTER TABLE {SqlGeneration.QuoteIdentifier(model.TableName, SqlGenerationDialect.Sqlite)} " +
                $"ADD CONSTRAINT {SqlGeneration.QuoteIdentifier(constraintName, SqlGenerationDialect.Sqlite)} " +
                $"FOREIGN KEY ({SqlGeneration.QuoteIdentifier(foreignKey.PropertyName, SqlGenerationDialect.Sqlite)}) " +
                $"REFERENCES {SqlGeneration.QuoteIdentifier(foreignKey.ReferencedTable, SqlGenerationDialect.Sqlite)}" +
                $"({SqlGeneration.QuoteIdentifier(foreignKey.ReferencedColumn, SqlGenerationDialect.Sqlite)}){onDelete}";
            sb.AppendLine($"    internal const string FK_{foreignKey.PropertyName} = {ToCSharpLiteral(sql)};");
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    internal static string ToCSharpLiteral(string value)
        => SymbolDisplay.FormatLiteral(value, quote: true);

    internal static string BuildCreateTable(TableModel model)
    {
        var columns = new List<string>();
        foreach (ColumnModel column in model.Columns.AsSpan())
        {
            string dbType = column.IsPrimaryKey && column.IsAutoIncrement
                ? "INTEGER"
                : column.DbTypeName;
            string generated = column.ComputedExpression is null
                ? ""
                : $" GENERATED ALWAYS AS ({column.ComputedExpression}) STORED";
            string nullable = column.IsRequired ? " NOT NULL" : "";
            string primaryKey = column.IsPrimaryKey && column.IsAutoIncrement
                ? " PRIMARY KEY AUTOINCREMENT"
                : column.IsPrimaryKey ? " PRIMARY KEY" : "";
            columns.Add($"    {column.ColumnName} {dbType}{generated}{nullable}{primaryKey}");
        }

        return $"CREATE TABLE IF NOT EXISTS {model.TableName} (\n" +
            $"{string.Join(",\n", columns)}\n)";
    }

    internal static string BuildCreateTable(
        TableModel model,
        SqlGenerationDialect dialect)
    {
        var columns = new List<string>();
        foreach (ColumnModel column in model.Columns.AsSpan())
        {
            string name = SqlGeneration.QuoteIdentifier(column.ColumnName, dialect);
            string dbType = GetDbType(column, dialect);
            string generated = column.ComputedExpression is null
                ? ""
                : $" GENERATED ALWAYS AS ({column.ComputedExpression}) STORED";
            string nullable = column.IsRequired ? " NOT NULL" : "";
            string primaryKey = GetPrimaryKeyClause(column, dialect);
            columns.Add($"    {name} {dbType}{generated}{primaryKey}{nullable}");
        }

        string tableName = SqlGeneration.QuoteIdentifier(model.TableName, dialect);
        return $"CREATE TABLE IF NOT EXISTS {tableName} (\n" +
            $"{string.Join(",\n", columns)}\n)";
    }

    private static string GetPrimaryKeyClause(
        ColumnModel column,
        SqlGenerationDialect dialect)
    {
        if (!column.IsPrimaryKey) return "";
        if (!column.IsAutoIncrement) return " PRIMARY KEY";

        return dialect switch
        {
            SqlGenerationDialect.Sqlite => " PRIMARY KEY AUTOINCREMENT",
            SqlGenerationDialect.PostgreSql => " GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
            SqlGenerationDialect.MySql => " AUTO_INCREMENT PRIMARY KEY",
            _ => throw new ArgumentOutOfRangeException(nameof(dialect))
        };
    }

    private static string GetDbType(
        ColumnModel column,
        SqlGenerationDialect dialect)
    {
        if (column.IsAutoIncrement && dialect == SqlGenerationDialect.Sqlite)
            return "INTEGER";

        string typeName = column.ProviderClrTypeName;
        if (typeName is "long" or "global::System.Int64") return "BIGINT";
        if (typeName is "int" or "global::System.Int32") return "INTEGER";
        if (typeName is "short" or "global::System.Int16" or
            "byte" or "global::System.Byte") return "SMALLINT";
        if (typeName is "bool" or "global::System.Boolean") return "BOOLEAN";
        if (typeName is "decimal" or "global::System.Decimal") return "DECIMAL";
        if (typeName is "double" or "global::System.Double")
            return dialect == SqlGenerationDialect.PostgreSql ? "DOUBLE PRECISION" : "DOUBLE";
        if (typeName is "float" or "global::System.Single") return "REAL";
        if (typeName is "global::System.DateOnly") return "DATE";
        if (typeName is "global::System.TimeOnly")
            return dialect == SqlGenerationDialect.MySql ? "TIME(6)" : "TIME";
        if (typeName is "global::System.DateTime")
            return dialect == SqlGenerationDialect.MySql ? "DATETIME(6)" : "TIMESTAMP";
        if (typeName is "global::System.DateTimeOffset")
            return dialect switch
            {
                SqlGenerationDialect.Sqlite => "TEXT",
                SqlGenerationDialect.PostgreSql => "TIMESTAMPTZ",
                SqlGenerationDialect.MySql => "DATETIME(6)",
                _ => throw new ArgumentOutOfRangeException(nameof(dialect))
            };
        if (typeName is "global::System.Guid")
            return dialect switch
            {
                SqlGenerationDialect.Sqlite => "TEXT",
                SqlGenerationDialect.PostgreSql => "UUID",
                SqlGenerationDialect.MySql => "CHAR(36)",
                _ => throw new ArgumentOutOfRangeException(nameof(dialect))
            };
        if (typeName is "char" or "global::System.Char") return "TEXT";
        if (typeName is "string" or "global::System.String")
            return dialect == SqlGenerationDialect.MySql && column.IsPrimaryKey
                ? "VARCHAR(255)"
                : "TEXT";
        return column.DbTypeName;
    }
}
