using System.Text;
using Microsoft.CodeAnalysis.CSharp;

namespace PalORM.SourceGen;

/// <summary>迁移 DDL 代码生成器——为 [Table] 类生成 CREATE TABLE/INDEX/FOREIGN KEY 语句。</summary>
internal static class MigrationEmitter
{
    internal static string Generate(TableModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace PalORM.Generated;");
        sb.AppendLine();
        sb.AppendLine("[global::System.CodeDom.Compiler.GeneratedCode(\"PalORM.SourceGen\", \"2.0.0\")]");
        sb.AppendLine($"internal static class Migration_{model.GeneratedTypeSuffix}");
        sb.AppendLine("{");

        string legacy = BuildCreateTable(model);
        string sqlite = BuildCreateTable(model, SqlGenerationDialect.Sqlite);
        string postgreSql = BuildCreateTable(model, SqlGenerationDialect.PostgreSql);
        string mySql = BuildCreateTable(model, SqlGenerationDialect.MySql);
        sb.AppendLine($"    internal const string CreateTable = {ToCSharpLiteral(legacy)};");
        sb.AppendLine($"    internal const string CreateTableSqlite = {ToCSharpLiteral(sqlite)};");
        sb.AppendLine($"    internal const string CreateTablePostgreSql = {ToCSharpLiteral(postgreSql)};");
        sb.AppendLine($"    internal const string CreateTableMySql = {ToCSharpLiteral(mySql)};");

        // 索引 DDL（ADR-B）：三方言各一组，MigrateAsync 按 Provider 方言执行。
        // FK 约束仍不生成（SQLite 需内联 CREATE TABLE，留待迁移系统整体设计）——由 PALORM017 告警。
        sb.AppendLine();
        AppendIndexArray(sb, model, "CreateIndexesSqlite", SqlGenerationDialect.Sqlite);
        AppendIndexArray(sb, model, "CreateIndexesPostgreSql", SqlGenerationDialect.PostgreSql);
        AppendIndexArray(sb, model, "CreateIndexesMySql", SqlGenerationDialect.MySql);

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void AppendIndexArray(
        StringBuilder sb, TableModel model, string fieldName, SqlGenerationDialect dialect)
    {
        if (model.Indexes.AsSpan().Length == 0)
        {
            sb.AppendLine($"    internal static readonly string[] {fieldName} = global::System.Array.Empty<string>();");
            return;
        }
        sb.AppendLine($"    internal static readonly string[] {fieldName} =");
        sb.AppendLine("    [");
        foreach (IndexModel index in model.Indexes.AsSpan())
            sb.AppendLine($"        {ToCSharpLiteral(BuildCreateIndex(model, index, dialect))},");
        sb.AppendLine("    ];");
    }

    internal static string BuildCreateIndex(
        TableModel model, IndexModel index, SqlGenerationDialect dialect)
    {
        string unique = index.Unique ? "UNIQUE " : "";
        // MySQL 不支持 CREATE INDEX IF NOT EXISTS——幂等由运行时 IsDuplicateSchemaObject 兜底
        string ifNotExists = dialect == SqlGenerationDialect.MySql ? "" : "IF NOT EXISTS ";
        string columns = string.Join(", ", index.Columns.AsSpan().ToArray()
            .Select(column => SqlGeneration.QuoteIdentifier(column, dialect)));
        return $"CREATE {unique}INDEX {ifNotExists}" +
            $"{SqlGeneration.QuoteIdentifier(index.Name, dialect)} ON " +
            $"{SqlGeneration.QuoteIdentifier(model.TableName, dialect)} ({columns})";
    }

    internal static string ToCSharpLiteral(string value)
        => SymbolDisplay.FormatLiteral(value, quote: true);

    /// <summary>legacy 单方言 DDL——填充注册表 CreateTableSql（MigrateAsync 在
    /// CreateTableSqlByDialect 缺键时的回退）。标识符引用与方言重载对齐（SQLite/PG
    /// 风格双引号）；列型走 DbTypeName 原值，与方言重载的类型映射刻意不同。</summary>
    internal static string BuildCreateTable(TableModel model)
    {
        List<string> columns = [];
        foreach (ColumnModel column in model.Columns.AsSpan())
        {
            string name = SqlGeneration.QuoteIdentifier(column.ColumnName, SqlGenerationDialect.Sqlite);
            string dbType = column.IsPrimaryKey && column.IsAutoIncrement
                ? "INTEGER"
                : column.DbTypeName;
            string generated = column.ComputedExpression is null
                ? ""
                : $" GENERATED ALWAYS AS ({column.ComputedExpression}) STORED";
            // NOT NULL 语义源与 RowFactory 的 IsDBNull 守卫合一（ITM-312）：
            // 非可空注解列（IsNullable=false）物化时不做 DBNull 检查，DDL 必须同步 NOT NULL，
            // 否则外部写入 NULL 后读取直接抛异常
            string nullable = column.IsRequired || (!column.IsNullable && !column.IsPrimaryKey)
                ? " NOT NULL" : "";
            // [Timestamp] 列被排除出 INSERT——NOT NULL 无 DEFAULT 时每次插入必失败（ITM-402）。
            // ITM-519：DEFAULT CURRENT_TIMESTAMP 仅对 DateTime/DateTimeOffset 合法；
            // TimeOnly/DateOnly/数值等类型上会生成 MySQL 非法 DDL，这些类型不加 DEFAULT。
            string defaultClause = column.IsTimestamp && IsTemporalTimestampType(column)
                ? " DEFAULT CURRENT_TIMESTAMP" : "";
            string primaryKey = column.IsPrimaryKey && column.IsAutoIncrement
                ? " PRIMARY KEY AUTOINCREMENT"
                : column.IsPrimaryKey ? " PRIMARY KEY" : "";
            columns.Add($"    {name} {dbType}{generated}{nullable}{defaultClause}{primaryKey}");
        }

        return $"CREATE TABLE IF NOT EXISTS {SqlGeneration.QuoteIdentifier(model.TableName, SqlGenerationDialect.Sqlite)} (\n" +
            $"{string.Join(",\n", columns)}\n)";
    }

    internal static string BuildCreateTable(
        TableModel model,
        SqlGenerationDialect dialect)
    {
        List<string> columns = [];
        foreach (ColumnModel column in model.Columns.AsSpan())
        {
            string name = SqlGeneration.QuoteIdentifier(column.ColumnName, dialect);
            string dbType = GetDbType(column, dialect, IsIndexed(model, column));
            string generated = column.ComputedExpression is null
                ? ""
                : $" GENERATED ALWAYS AS ({column.ComputedExpression}) STORED";
            // NOT NULL 语义源与 RowFactory 的 IsDBNull 守卫合一（ITM-312）：
            // 非可空注解列（IsNullable=false）物化时不做 DBNull 检查，DDL 必须同步 NOT NULL，
            // 否则外部写入 NULL 后读取直接抛异常
            string nullable = column.IsRequired || (!column.IsNullable && !column.IsPrimaryKey)
                ? " NOT NULL" : "";
            // [Timestamp] 列被排除出 INSERT——NOT NULL 无 DEFAULT 时每次插入必失败（ITM-402）。
            // MySQL 分秒精度列要求 DEFAULT 表达式精度一致（DATETIME(6) 需 CURRENT_TIMESTAMP(6)）。
            // ITM-519：DEFAULT CURRENT_TIMESTAMP 仅对 DateTime/DateTimeOffset 合法——
            // TimeOnly/DateOnly 上 MySQL 会拒绝该 DEFAULT，非时间戳类型一律不加。
            string defaultClause = column.IsTimestamp && IsTemporalTimestampType(column)
                ? dialect == SqlGenerationDialect.MySql && dbType.EndsWith("(6)", StringComparison.Ordinal)
                    ? " DEFAULT CURRENT_TIMESTAMP(6)"
                    : " DEFAULT CURRENT_TIMESTAMP"
                : "";
            string primaryKey = GetPrimaryKeyClause(column, dialect);
            columns.Add($"    {name} {dbType}{generated}{primaryKey}{nullable}{defaultClause}");
        }

        string tableName = SqlGeneration.QuoteIdentifier(model.TableName, dialect);
        return $"CREATE TABLE IF NOT EXISTS {tableName} (\n" +
            $"{string.Join(",\n", columns)}\n)";
    }

    private static string GetPrimaryKeyClause(
        ColumnModel column,
        SqlGenerationDialect dialect)
    {
        if (!column.IsPrimaryKey) return "";
        if (!column.IsAutoIncrement) return " PRIMARY KEY";

        return dialect switch
        {
            SqlGenerationDialect.Sqlite => " PRIMARY KEY AUTOINCREMENT",
            SqlGenerationDialect.PostgreSql => " GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
            SqlGenerationDialect.MySql => " AUTO_INCREMENT PRIMARY KEY",
            _ => throw new ArgumentOutOfRangeException(nameof(dialect))
        };
    }

    /// <summary>[Timestamp] 列的 CLR 类型是否为可承载 CURRENT_TIMESTAMP 的时间戳类型（ITM-519）。
    /// 仅 DateTime/DateTimeOffset 在三方言下均接受 DEFAULT CURRENT_TIMESTAMP；
    /// TimeOnly/DateOnly 等在 MySQL 上会产出非法 DDL，故这些类型不生成该 DEFAULT。</summary>
    private static bool IsTemporalTimestampType(ColumnModel column)
        => column.ProviderClrTypeName is
            "global::System.DateTime" or "global::System.DateTimeOffset";

    /// <summary>列是否被任何 [Index]/[Unique] 索引引用——决定 MySQL 下 string 列型。</summary>
    private static bool IsIndexed(TableModel model, ColumnModel column)
    {
        foreach (IndexModel index in model.Indexes.AsSpan())
        {
            foreach (string indexColumn in index.Columns.AsSpan())
            {
                if (string.Equals(indexColumn, column.ColumnName, StringComparison.Ordinal))
                    return true;
            }
        }
        return false;
    }

    private static string GetDbType(
        ColumnModel column,
        SqlGenerationDialect dialect,
        bool isIndexed = false)
    {
        if (column.IsAutoIncrement && dialect == SqlGenerationDialect.Sqlite)
            return "INTEGER";

        string typeName = column.ProviderClrTypeName;
        if (typeName is "long" or "global::System.Int64") return "BIGINT";
        if (typeName is "int" or "global::System.Int32") return "INTEGER";
        if (typeName is "short" or "global::System.Int16" or
            "byte" or "global::System.Byte") return "SMALLINT";
        if (typeName is "bool" or "global::System.Boolean") return "BOOLEAN";
        // 裸 DECIMAL 在 MySQL 即 DECIMAL(10,0)——小数静默截断；三方言统一显式精度
        if (typeName is "decimal" or "global::System.Decimal") return "DECIMAL(18,6)";
        if (typeName is "double" or "global::System.Double")
            return dialect == SqlGenerationDialect.PostgreSql ? "DOUBLE PRECISION" : "DOUBLE";
        if (typeName is "float" or "global::System.Single") return "REAL";
        if (typeName is "global::System.DateOnly") return "DATE";
        if (typeName is "global::System.TimeOnly")
            return dialect == SqlGenerationDialect.MySql ? "TIME(6)" : "TIME";
        if (typeName is "global::System.DateTime")
            return dialect == SqlGenerationDialect.MySql ? "DATETIME(6)" : "TIMESTAMP";
        if (typeName is "global::System.DateTimeOffset")
            return dialect switch
            {
                SqlGenerationDialect.Sqlite => "TEXT",
                SqlGenerationDialect.PostgreSql => "TIMESTAMPTZ",
                SqlGenerationDialect.MySql => "DATETIME(6)",
                _ => throw new ArgumentOutOfRangeException(nameof(dialect))
            };
        if (typeName is "global::System.Guid")
            return dialect switch
            {
                SqlGenerationDialect.Sqlite => "TEXT",
                SqlGenerationDialect.PostgreSql => "UUID",
                SqlGenerationDialect.MySql => "CHAR(36)",
                _ => throw new ArgumentOutOfRangeException(nameof(dialect))
            };
        if (typeName is "char" or "global::System.Char")
            // ITM-566：1170 规避对所有落 TEXT 的类型统一——char 被索引/主键时同 string 处理
            return dialect == SqlGenerationDialect.MySql && (column.IsPrimaryKey || isIndexed)
                ? "VARCHAR(255)"
                : "TEXT";
        if (typeName is "string" or "global::System.String")
            // MySQL 对 TEXT/BLOB 建索引必须指定前缀长度（错误 1170，不被 1061 幂等兜底吞）——
            // 主键列与被索引列一律 VARCHAR(255)（ITM-201）
            return dialect == SqlGenerationDialect.MySql && (column.IsPrimaryKey || isIndexed)
                ? "VARCHAR(255)"
                : "TEXT";
        // ITM-566：兜底 TEXT（enum/未识别类型）同受 1170 约束——被索引时 VARCHAR(255)
        if (dialect == SqlGenerationDialect.MySql && (column.IsPrimaryKey || isIndexed)
            && column.DbTypeName == "TEXT")
            return "VARCHAR(255)";
        return column.DbTypeName;
    }
}
