// <auto-generated/>
// Phase 1 PoC：Auto Tagging Interceptor 端到端验证。
// 仅拦截 ToListAsync 单方法；PoC 通过后由 AutoTaggingEmitter.cs（完整 6 方法版）替换。
#pragma warning disable RS1035 // 禁止 IO API — PoC 不执行 IO
#pragma warning disable CS1591 // 缺少 XML 注释
#nullable enable

using System.Collections.Immutable;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Operations;

namespace PalORM.SourceGen;

/// <summary>
/// PoC：扫描 ToListAsync 调用，生成 [InterceptsLocation] 拦截方法。
/// 验证端到端链路：SyntaxProvider → GetInterceptableLocation → 生成代码 → 编译器重写调用点。
/// </summary>
internal static class PoCAutoTaggingEmitter
{
    /// <summary>谓词：节点是 ToListAsync 的 InvocationExpression。</summary>
    public static bool IsToListAsyncCall(SyntaxNode node)
    {
        return node is InvocationExpressionSyntax invocation
            && invocation.Expression is MemberAccessExpressionSyntax member
            && member.Name.Identifier.Text == "ToListAsync";
    }

    /// <summary>转换：提取调用点的 InterceptableLocation + 路径/行号/方法名。</summary>
    public static PoCTarget? ExtractTarget(GeneratorSyntaxContext ctx, CancellationToken ct)
    {
        var invocation = (InvocationExpressionSyntax)ctx.Node;
        if (ctx.SemanticModel.GetOperation(invocation, ct) is not IInvocationOperation op)
            return null;
        // 过滤：必须是 QueryBuilderExtensions.ToListAsync（排除其他同名方法）
        if (op.TargetMethod.ContainingType?.Name != "QueryBuilderExtensions")
            return null;
        // 假设 A 核心调用：GetInterceptableLocation 扩展方法
        InterceptableLocation? location = ctx.SemanticModel.GetInterceptableLocation(invocation, ct);
        if (location is null) return null;

        // 提取调用点位置信息（用于 Tag 注释）
        Location loc = invocation.GetLocation();
        FileLinePositionSpan span = loc.GetLineSpan();
        string filePath = span.Path;
        int line = span.StartLinePosition.Line + 1; // 0-based 转 1-based
        // 提取调用方法名（用包含语句的父节点查）
        string memberName = FindEnclosingMemberName(invocation);

        return new PoCTarget(location, filePath, line, memberName);
    }

    /// <summary>生成拦截器源代码（单个 ToListAsync 拦截方法）。</summary>
    public static string Generate(ImmutableArray<PoCTarget?> targets)
    {
        var sb = new System.Text.StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        // InterceptsLocationAttribute 必须定义在 System.Runtime.CompilerServices——编译器硬编码要求。
        // 拦截器类型放 PalORM.Generated（需在 InterceptorsNamespaces 声明）。
        // 用两个 block namespace（非 file-scoped）避免 CS8954（文件只能含一个 file-scoped namespace）。
        sb.AppendLine("namespace System.Runtime.CompilerServices");
        sb.AppendLine("{");
        sb.AppendLine("    [System.AttributeUsage(System.AttributeTargets.Method, AllowMultiple = true)]");
        sb.AppendLine("    internal sealed class InterceptsLocationAttribute : System.Attribute");
        sb.AppendLine("    {");
        sb.AppendLine("        public InterceptsLocationAttribute(int version, string data) { }");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("namespace PalORM.Generated");
        sb.AppendLine("{");
        sb.AppendLine("    [global::System.CodeDom.Compiler.GeneratedCode(\"PalORM.SourceGen\", \"2.0.0\")]");
        sb.AppendLine("    internal static class PoCAutoTaggingInterceptor");
        sb.AppendLine("    {");

        int index = 0;
        foreach (PoCTarget? target in targets)
        {
            if (target is null) continue;
            // [InterceptsLocation(version, data)] —— data 来自 GetInterceptableLocation，不可手写。
            // GetInterceptsLocationAttributeSyntax 输出 global::System.Runtime.CompilerServices.InterceptsLocationAttribute(version, data)。
            sb.AppendLine($"        {target.Value.Location.GetInterceptsLocationAttributeSyntax()}");
            // 注释内容：相对路径 + 行号 + 成员名（PoC 暂用绝对路径，Phase 2 做路径规范化）
            string tag = $"{target.Value.FilePath}:{target.Value.Line} {target.Value.MemberName}";
            // 转义 Tag 字符串中的特殊字符
            string escapedTag = tag.Replace("\\", "\\\\").Replace("\"", "\\\"");
            sb.AppendLine($"        internal static async global::System.Threading.Tasks.ValueTask<global::System.Collections.Generic.List<T>>");
            sb.AppendLine($"            ToListAsync_AutoTag_{index}<T>(this global::PalORM.QueryBuilder<T> builder,");
            sb.AppendLine($"                global::System.Threading.CancellationToken ct = default)");
            sb.AppendLine($"            where T : class, new()");
            sb.AppendLine("        {");
            sb.AppendLine($"            return await builder.Tag(\"{escapedTag}\").ToListAsync(ct).ConfigureAwait(false);");
            sb.AppendLine("        }");
            sb.AppendLine();
            index++;
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    /// <summary>从调用点向上查找包含的成员名（方法/属性）。</summary>
    private static string FindEnclosingMemberName(SyntaxNode node)
    {
        SyntaxNode? current = node.Parent;
        while (current is not null)
        {
            if (current is MethodDeclarationSyntax method)
                return method.Identifier.Text;
            if (current is PropertyDeclarationSyntax prop)
                return prop.Identifier.Text;
            current = current.Parent;
        }
        return "unknown";
    }

    /// <summary>PoC 调用点目标。</summary>
    public readonly record struct PoCTarget(
        InterceptableLocation Location,
        string FilePath,
        int Line,
        string MemberName);
}
