using System.Text;

namespace PalORM.SourceGen;

/// <summary>R1（v6.0）：[Projection] 只读物化类型的发射器。
/// <para>RowFactory 完整复用 <see cref="RowFactoryEmitter"/>（伪 TableModel——其生成物仅消费
/// Columns 与类型名，表名/索引/FK 不参与物化路径）；注册走独立 ModuleInitializer 片段：
/// 只填 RowFactories，其余 required 字典空集（TableNames 空 = 片段实体全集空，required 字典
/// SetEquals 校验放行；RowFactories 走 PalORM_Runtime.Register 的超集校验，纯投影键合法）。</para></summary>
internal static class ProjectionEmitter
{
    internal static string GenerateRowFactory(ProjectionModel model)
        => RowFactoryEmitter.Generate(new TableModel(
            model.Namespace, model.ClassName, model.EntityTypeName, model.GeneratedTypeSuffix,
            TableName: model.ClassName,  // RowFactoryEmitter 不消费表名；占位维持 record 完整性
            IsSoftDelete: false, IsTenantAware: false,
            model.Columns,
            new EquatableArray<IndexModel>(System.Array.Empty<IndexModel>()),
            new EquatableArray<ForeignKeyModel>(System.Array.Empty<ForeignKeyModel>())));

    internal static string GenerateRegistry(EquatableArray<ProjectionModel> models)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace PalORM.Generated;");
        sb.AppendLine();
        sb.AppendLine(GeneratedCodeMetadata.GeneratedCodeAttribute);
        // [Projection] 物化注册——只读类型不进 TableNames（MigrateAsync 不建表）
        sb.AppendLine("internal static class PalORM_ProjectionRegistryInitializer");
        sb.AppendLine("{");
        sb.AppendLine("    [global::System.Runtime.CompilerServices.ModuleInitializer]");
        sb.AppendLine("    internal static void Initialize()");
        sb.AppendLine("    {");
        sb.AppendLine("        global::PalORM.PalORM_Runtime.Register(new global::PalORM.RegistryFragment");
        sb.AppendLine("        {");
        sb.AppendLine("            RowFactories = new global::System.Collections.Generic.Dictionary<global::System.Type, object>");
        sb.AppendLine("            {");
        // EntityTypeName 排序——保证注册文件字节级确定（Collect 顺序在增量编译间可变，
        // 未排序会导致生成文件抖动、增量缓存失效）
        foreach (ProjectionModel model in models.AsSpan().ToArray()
                     .OrderBy(static m => m.EntityTypeName, StringComparer.Ordinal))
            sb.AppendLine($"                [typeof({model.EntityTypeName})] = RowFactory_{model.GeneratedTypeSuffix}.Read,");
        sb.AppendLine("            },");
        // 空集用 FrozenDictionary.Empty（生成物消费端为 net11；比逐字典 new Dictionary 短且零分配）。
        // required 字段类型对齐 RegistryFragment 声明（ColumnNames 值为 string[]、SetIdDelegates 不可缺）。
        sb.AppendLine("            TableNames = global::System.Collections.Frozen.FrozenDictionary<global::System.Type, string>.Empty,");
        sb.AppendLine("            BindInsert = global::System.Collections.Frozen.FrozenDictionary<global::System.Type, global::System.Action<global::System.Data.Common.DbCommand, object, int>>.Empty,");
        sb.AppendLine("            BindUpdate = global::System.Collections.Frozen.FrozenDictionary<global::System.Type, global::System.Action<global::System.Data.Common.DbCommand, object>>.Empty,");
        sb.AppendLine("            BindDelete = global::System.Collections.Frozen.FrozenDictionary<global::System.Type, global::System.Action<global::System.Data.Common.DbCommand, object>>.Empty,");
        sb.AppendLine("            PkColumns = global::System.Collections.Frozen.FrozenDictionary<global::System.Type, string>.Empty,");
        sb.AppendLine("            ColumnNames = global::System.Collections.Frozen.FrozenDictionary<global::System.Type, string[]>.Empty,");
        sb.AppendLine("            PropertyToColumn = global::System.Collections.Frozen.FrozenDictionary<global::System.Type, global::System.Collections.Generic.IReadOnlyDictionary<string, string>>.Empty,");
        sb.AppendLine("            CrudMetadatas = global::System.Collections.Frozen.FrozenDictionary<global::System.Type, global::PalORM.CrudMetadata>.Empty,");
        sb.AppendLine("            EntityFeatures = global::System.Collections.Frozen.FrozenDictionary<global::System.Type, global::PalORM.EntityFeatures>.Empty,");
        sb.AppendLine("            SetIdDelegates = global::System.Collections.Frozen.FrozenDictionary<global::System.Type, global::System.Action<object, long>>.Empty,");
        sb.AppendLine("        });");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }
}
