using System.Text;

namespace PalORM.SourceGen;

internal static class RegistryEmitter
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Maintainability",
        "S3776:CognitiveComplexity",
        Justification = "Registry 注册代码生成器：每个注册字典（RowFactories/TableNames/...）按顺序 "
            + "Append 到 StringBuilder。线性结构清晰，按字典拆分 Append* 方法会复制 14 次 foreach "
            + "样板，反而损害可读性。快照测试已覆盖字节级输出正确性。")]
    internal static string Generate(EquatableArray<TableModel> models)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace PalORM.Generated;");
        sb.AppendLine();
        sb.AppendLine("[global::System.CodeDom.Compiler.GeneratedCode(\"PalORM.SourceGen\", \"2.0.0\")]");
        sb.AppendLine("internal static class PalORM_RegistryInitializer");
        sb.AppendLine("{");
        sb.AppendLine("    [global::System.Runtime.CompilerServices.ModuleInitializer]");
        sb.AppendLine("    internal static void Initialize()");
        sb.AppendLine("    {");
        sb.AppendLine("        global::PalORM.PalORM_Runtime.Register(new global::PalORM.RegistryFragment");
        sb.AppendLine("        {");
        sb.AppendLine("            RowFactories = new global::System.Collections.Generic.Dictionary<global::System.Type, object>");
        sb.AppendLine("        {");
        // v3.1: 注册 Func<DbDataReader, T> 委托（装箱为 object），替代旧的 RowFactory Instance。
        // 调用方从字典取出后强转为 Func<DbDataReader, T> 直接 invoke，消除接口虚分发。
        foreach (var m in models.AsSpan())
            sb.AppendLine($"            [typeof({m.EntityTypeName})] = RowFactory_{m.GeneratedTypeSuffix}.Read,");
        sb.AppendLine("        },");
        sb.AppendLine();
        sb.AppendLine("            TableNames = new global::System.Collections.Generic.Dictionary<global::System.Type, string>");
        sb.AppendLine("        {");
        foreach (var m in models.AsSpan())
            sb.AppendLine($"            [typeof({m.EntityTypeName})] = {MigrationEmitter.ToCSharpLiteral(m.TableName)},");
        sb.AppendLine("        },");
        sb.AppendLine();
        sb.AppendLine("            CommandSqls = new global::System.Collections.Generic.Dictionary<global::System.Type, global::PalORM.CommandSqlSet>");
        sb.AppendLine("        {");
        foreach (var m in models.AsSpan())
        {
            string ins = CommandFactoryEmitter.BuildInsertSql(m);
            string upd = CommandFactoryEmitter.BuildUpdateSql(m);
            string del = CommandFactoryEmitter.BuildDeleteSql(m);
            string ret = CommandFactoryEmitter.BuildInsertReturningSql(m);
            string uRet = CommandFactoryEmitter.BuildUpsertReturningSql(m);
            string uMy = CommandFactoryEmitter.BuildUpsertMySqlSql(m);
            string lId = CommandFactoryEmitter.BuildInsertWithLastInsertIdSql(m);
            sb.AppendLine($"            [typeof({m.EntityTypeName})] = new global::PalORM.CommandSqlSet(");
            sb.AppendLine($"                {MigrationEmitter.ToCSharpLiteral(ins)}, {MigrationEmitter.ToCSharpLiteral(upd)}, {MigrationEmitter.ToCSharpLiteral(del)}, {MigrationEmitter.ToCSharpLiteral(ret)}, {MigrationEmitter.ToCSharpLiteral(uRet)}, {MigrationEmitter.ToCSharpLiteral(uMy)}, {MigrationEmitter.ToCSharpLiteral(lId)}),");
        }
        sb.AppendLine("        },");
        sb.AppendLine();
        sb.AppendLine("            CommandSqlsByDialect = new global::System.Collections.Generic.Dictionary<global::System.Type, global::PalORM.CommandSqlByDialect>");
        sb.AppendLine("        {");
        foreach (var m in models.AsSpan())
        {
            sb.AppendLine($"            [typeof({m.EntityTypeName})] = new global::PalORM.CommandSqlByDialect(");
            AppendCommandSqlSet(sb, m, SqlGenerationDialect.Sqlite);
            AppendCommandSqlSet(sb, m, SqlGenerationDialect.PostgreSql);
            AppendCommandSqlSet(sb, m, SqlGenerationDialect.MySql, isLast: true);
            sb.AppendLine("            ),");
        }
        sb.AppendLine("        },");
        sb.AppendLine();
        sb.AppendLine("            BindInsert = new global::System.Collections.Generic.Dictionary<global::System.Type, global::System.Action<global::System.Data.Common.DbCommand, object, int>>");
        sb.AppendLine("        {");
        foreach (var m in models.AsSpan())
            sb.AppendLine($"            [typeof({m.EntityTypeName})] = (cmd, obj, off) => CommandFactory_{m.GeneratedTypeSuffix}.BindInsertToBatch(cmd, ({m.EntityTypeName})obj, off),");
        sb.AppendLine("        },");
        sb.AppendLine();
        sb.AppendLine("            BindUpdate = new global::System.Collections.Generic.Dictionary<global::System.Type, global::System.Action<global::System.Data.Common.DbCommand, object>>");
        sb.AppendLine("        {");
        foreach (var m in models.AsSpan())
            sb.AppendLine($"            [typeof({m.EntityTypeName})] = (cmd, obj) => CommandFactory_{m.GeneratedTypeSuffix}.BindUpdate(cmd, ({m.EntityTypeName})obj),");
        sb.AppendLine("        },");
        sb.AppendLine();
        sb.AppendLine("            BindDelete = new global::System.Collections.Generic.Dictionary<global::System.Type, global::System.Action<global::System.Data.Common.DbCommand, object>>");
        sb.AppendLine("        {");
        foreach (var m in models.AsSpan())
            sb.AppendLine($"            [typeof({m.EntityTypeName})] = (cmd, key) => CommandFactory_{m.GeneratedTypeSuffix}.BindDelete(cmd, key),");
        sb.AppendLine("        },");
        sb.AppendLine();
        sb.AppendLine("            CrudMetadatas = new global::System.Collections.Generic.Dictionary<global::System.Type, global::PalORM.CrudMetadata>");
        sb.AppendLine("        {");
        foreach (var m in models.AsSpan())
        {
            // CrudMetadata 用聚合 ctor（CrudBindings + CrudColumns）避免 9 参参数列表（S107）。
            sb.AppendLine($"            [typeof({m.EntityTypeName})] = new global::PalORM.CrudMetadata(");
            sb.AppendLine($"                new global::PalORM.CommandSqlSet(");
            sb.AppendLine($"                    CommandFactory_{m.GeneratedTypeSuffix}.InsertSql,");
            sb.AppendLine($"                    CommandFactory_{m.GeneratedTypeSuffix}.UpdateSql,");
            sb.AppendLine($"                    CommandFactory_{m.GeneratedTypeSuffix}.DeleteSql,");
            sb.AppendLine($"                    CommandFactory_{m.GeneratedTypeSuffix}.InsertReturningSql,");
            sb.AppendLine($"                    CommandFactory_{m.GeneratedTypeSuffix}.UpsertReturningSql,");
            sb.AppendLine($"                    CommandFactory_{m.GeneratedTypeSuffix}.UpsertMySqlSql,");
            sb.AppendLine($"                    CommandFactory_{m.GeneratedTypeSuffix}.InsertWithLastInsertIdSql),");
            sb.AppendLine($"                new global::PalORM.CrudBindings(");
            sb.AppendLine($"                    (cmd, obj, off) => CommandFactory_{m.GeneratedTypeSuffix}.BindInsertToBatch(cmd, ({m.EntityTypeName})obj, off),");
            sb.AppendLine($"                    (parameters, obj, off) => CommandFactory_{m.GeneratedTypeSuffix}.BindInsertValues(parameters, ({m.EntityTypeName})obj, off),");
            sb.AppendLine($"                    (cmd, obj) => CommandFactory_{m.GeneratedTypeSuffix}.BindUpsert(cmd, ({m.EntityTypeName})obj),");
            sb.AppendLine($"                    (cmd, obj) => CommandFactory_{m.GeneratedTypeSuffix}.BindUpdate(cmd, ({m.EntityTypeName})obj),");
            sb.AppendLine($"                    RowFactory_{m.GeneratedTypeSuffix}.Read),");
            // ITM-640：单次物化 Columns（原 6 处 AsSpan().ToArray() 重复分配，编译期路径）
            var columns = m.Columns.AsSpan().ToArray();
            string insertColumns = BuildStringArrayLiteral(
                columns.Where(static column => column.IsInsertable)
                    .Select(static column => column.ColumnName));
            string upsertColumns = BuildStringArrayLiteral(
                columns.Where(static column => column.IsUpsertable)
                    .Select(static column => column.ColumnName));
            sb.AppendLine($"                new global::PalORM.CrudColumns(");
            sb.AppendLine($"                    {insertColumns},");
            sb.AppendLine($"                    {upsertColumns}),");
            bool hasConcurrency = columns.Any(c => c.IsConcurrencyToken);
            sb.AppendLine(hasConcurrency
                ? $"                obj => CommandFactory_{m.GeneratedTypeSuffix}.IncrementVersion(({m.EntityTypeName})obj),"
                : "                null,");
            sb.AppendLine($"                obj => CommandFactory_{m.GeneratedTypeSuffix}.HasDefaultKey(({m.EntityTypeName})obj)),");
        }
        sb.AppendLine("        },");
        sb.AppendLine();
        sb.AppendLine("            EntityFeatures = new global::System.Collections.Generic.Dictionary<global::System.Type, global::PalORM.EntityFeatures>");
        sb.AppendLine("        {");
        foreach (var m in models.AsSpan())
        {
            // 按位组合 SoftDelete/TenantAware 特性；两者皆无则 None。
            var parts = new List<string>(2);
            if (m.IsSoftDelete) parts.Add("global::PalORM.EntityFeatures.SoftDelete");
            if (m.IsTenantAware) parts.Add("global::PalORM.EntityFeatures.TenantAware");
            string features = parts.Count == 0
                ? "global::PalORM.EntityFeatures.None"
                : string.Join(" | ", parts);
            sb.AppendLine($"            [typeof({m.EntityTypeName})] = {features},");
        }
        sb.AppendLine("        },");
        sb.AppendLine();
        sb.AppendLine("            PkColumns = new global::System.Collections.Generic.Dictionary<global::System.Type, string>");
        sb.AppendLine("        {");
        foreach (var m in models.AsSpan())
        {
            var pk = m.Columns.AsSpan().ToArray().FirstOrDefault(c => c.IsPrimaryKey);
            // ITM-581: CanGenerateEntity 契约保证恰一个 [Key]——此处缺 PK 是上游破坏，
            // 静默兜底 "id" 会让错误列名进注册表，改为立即失败暴露契约破坏点
            string pkName = pk?.ColumnName ?? throw new InvalidOperationException(
                $"Entity '{m.EntityTypeName}' reached RegistryEmitter without a primary key column; " +
                "CanGenerateEntity should have rejected it.");
            sb.AppendLine($"            [typeof({m.EntityTypeName})] = {MigrationEmitter.ToCSharpLiteral(pkName)},");
        }
        sb.AppendLine("        },");
        sb.AppendLine();
        sb.AppendLine("            ColumnNames = new global::System.Collections.Generic.Dictionary<global::System.Type, string[]>");
        sb.AppendLine("        {");
        foreach (var m in models.AsSpan())
        {
            string names = BuildStringArrayLiteral(
                m.Columns.AsSpan().ToArray().Select(static column => column.ColumnName));
            sb.AppendLine($"            [typeof({m.EntityTypeName})] = {names},");
        }
        sb.AppendLine("        },");
        sb.AppendLine();
        sb.AppendLine("            PropertyToColumn = new global::System.Collections.Generic.Dictionary<global::System.Type, global::System.Collections.Generic.IReadOnlyDictionary<string, string>>");
        sb.AppendLine("        {");
        foreach (var m in models.AsSpan())
        {
            sb.AppendLine($"            [typeof({m.EntityTypeName})] = new global::System.Collections.Generic.Dictionary<string, string>");
            sb.AppendLine("            {");
            foreach (var column in m.Columns.AsSpan())
                sb.AppendLine($"                [{MigrationEmitter.ToCSharpLiteral(column.PropertyName)}] = {MigrationEmitter.ToCSharpLiteral(column.ColumnName)},");
            sb.AppendLine("            },");
        }
        sb.AppendLine("        },");
        sb.AppendLine();
        sb.AppendLine("            CreateTableSql = new global::System.Collections.Generic.Dictionary<global::System.Type, string>");
        sb.AppendLine("        {");
        foreach (var m in models.AsSpan())
        {
            string ddl = MigrationEmitter.BuildCreateTable(m);
            sb.AppendLine(
                $"            [typeof({m.EntityTypeName})] = " +
                $"{MigrationEmitter.ToCSharpLiteral(ddl)},");
        }
        sb.AppendLine("        },");
        sb.AppendLine();
        sb.AppendLine("            CreateTableSqlByDialect = new global::System.Collections.Generic.Dictionary<global::System.Type, global::PalORM.CreateTableSqlSet>");
        sb.AppendLine("        {");
        foreach (var m in models.AsSpan())
        {
            sb.AppendLine($"            [typeof({m.EntityTypeName})] = new global::PalORM.CreateTableSqlSet(");
            sb.AppendLine($"                Migration_{m.GeneratedTypeSuffix}.CreateTableSqlite,");
            sb.AppendLine($"                Migration_{m.GeneratedTypeSuffix}.CreateTablePostgreSql,");
            sb.AppendLine($"                Migration_{m.GeneratedTypeSuffix}.CreateTableMySql),");
        }
        sb.AppendLine("        },");
        sb.AppendLine();
        sb.AppendLine("            CreateIndexSqlByDialect = new global::System.Collections.Generic.Dictionary<global::System.Type, global::PalORM.CreateIndexSqlSet>");
        sb.AppendLine("        {");
        foreach (var m in models.AsSpan())
        {
            if (m.Indexes.AsSpan().Length == 0) continue;
            sb.AppendLine($"            [typeof({m.EntityTypeName})] = new global::PalORM.CreateIndexSqlSet(");
            sb.AppendLine($"                Migration_{m.GeneratedTypeSuffix}.CreateIndexesSqlite,");
            sb.AppendLine($"                Migration_{m.GeneratedTypeSuffix}.CreateIndexesPostgreSql,");
            sb.AppendLine($"                Migration_{m.GeneratedTypeSuffix}.CreateIndexesMySql),");
        }
        sb.AppendLine("        },");
        sb.AppendLine();
        sb.AppendLine("            SetIdDelegates = new global::System.Collections.Generic.Dictionary<global::System.Type, global::System.Action<object, long>>");
        sb.AppendLine("        {");
        foreach (var m in models.AsSpan())
        {
            bool hasGeneratedKey = m.Columns.AsSpan().ToArray()
                .Any(static column => column.IsPrimaryKey && column.IsAutoIncrement);
            if (hasGeneratedKey)
                sb.AppendLine($"            [typeof({m.EntityTypeName})] = (entity, id) => CommandFactory_{m.GeneratedTypeSuffix}.SetId(({m.EntityTypeName})entity, id),");
        }
        sb.AppendLine("        },");
        sb.AppendLine("        });");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void AppendCommandSqlSet(
        StringBuilder builder,
        TableModel model,
        SqlGenerationDialect dialect,
        bool isLast = false)
    {
        string insert = CommandFactoryEmitter.BuildInsertSql(model, dialect);
        string update = CommandFactoryEmitter.BuildUpdateSql(model, dialect);
        string delete = CommandFactoryEmitter.BuildDeleteSql(model, dialect);
        string returning = CommandFactoryEmitter.BuildInsertReturningSql(model, dialect);
        string upsertReturning = CommandFactoryEmitter.BuildUpsertReturningSql(model, dialect);
        string upsertMySql = CommandFactoryEmitter.BuildUpsertMySqlSql(model, dialect);
        string insertLastId = CommandFactoryEmitter.BuildInsertWithLastInsertIdSql(model, dialect);
        builder.AppendLine("                new global::PalORM.CommandSqlSet(");
        builder.AppendLine($"                    {MigrationEmitter.ToCSharpLiteral(insert)},");
        builder.AppendLine($"                    {MigrationEmitter.ToCSharpLiteral(update)},");
        builder.AppendLine($"                    {MigrationEmitter.ToCSharpLiteral(delete)},");
        builder.AppendLine($"                    {MigrationEmitter.ToCSharpLiteral(returning)},");
        builder.AppendLine($"                    {MigrationEmitter.ToCSharpLiteral(upsertReturning)},");
        builder.AppendLine($"                    {MigrationEmitter.ToCSharpLiteral(upsertMySql)},");
        builder.AppendLine($"                    {MigrationEmitter.ToCSharpLiteral(insertLastId)}){(isLast ? "" : ",")}");
    }

    private static string BuildStringArrayLiteral(IEnumerable<string> values)
    {
        string[] items = values.ToArray();
        if (items.Length == 0)
            return "global::System.Array.Empty<string>()";

        return "new[] { " + string.Join(", ",
            items.Select(MigrationEmitter.ToCSharpLiteral)) + " }";
    }
}
