using System.Text;

namespace PalORM.SourceGen;

internal static class RegistryEmitter
{
    /// <summary>单块 IL 预算（估算值）——累计估算超过它即切块。
    /// <para><b>为什么分块</b>：注册代码原先全部落在单个 <c>[ModuleInitializer] Initialize()</c> 里，
    /// IL 随实体数线性增长——500 实体即**单方法 611,449 B IL**。实测（<c>RegistryScaleTests</c>，
    /// 3 样本/侧）把同一份 IL 摊到 22 个方法后，全部方法的 JIT 编译耗时中位数从 1299.2 ms 降到
    /// 376.8 ms（−71%）：超大方法的 JIT 成本是**超线性**的，分块不只是"把风险摊开"。</para>
    /// <para><b>为什么不是"每块各自调 Register"</b>：<c>PalORM_Runtime.Register</c> 每次调用都会
    /// 复制并重建当前累计状态——逐块调用会把 15 个字典反复拷贝，N 块累计 O(N²/块) 次插入。
    /// 因此分块只切**构建**：所有块写进同一个 draft，最后仍是一次 <c>Register</c>。</para>
    /// <para><b>为什么按估算 IL 而不是固定实体数</b>：单实体 IL 随列数增长（实测 4 列实体
    /// ≈1089 B/实体），固定"每块 25 个实体"在宽表上会重新撑破方法体——20 列实体单块可达 80 KB。
    /// 按估算切块后，块大小与实体数、列宽都解耦。</para></summary>
    private const int ChunkIlBudget = 24 * 1024;

    /// <summary>每实体固定开销的 IL 估算（21 条方言 SQL 字面量、15 个字典插入、
    /// 委托赋值、表名/主键/特性等与列数无关的部分）。</summary>
    private const int PerEntityIlEstimate = 900;

    /// <summary>每列开销的 IL 估算（PropertyToColumn 逐列一条、列名数组逐列一项等）。
    /// 由两个实测点反解——4 列实体 1032 B/实体、30 列实体 2392 B/实体 →
    /// 斜率 (2392−1032)/26 ≈ 52，截距 ≈823。两处都取整偏高约 10%，即估算偏保守、块偏小。</summary>
    private const int PerColumnIlEstimate = 60;

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Maintainability",
        "S3776:CognitiveComplexity",
        Justification = "Registry 注册代码生成器：每个注册字典（RowFactories/TableNames/...）按顺序 "
            + "Append 到 StringBuilder。线性结构清晰，按字典拆分 Append* 方法会复制 15 次 foreach "
            + "样板，反而损害可读性。快照测试已覆盖字节级输出正确性。")]
    internal static string Generate(EquatableArray<TableModel> models)
    {
        TableModel[] all = models.AsSpan().ToArray();
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace PalORM.Generated;");
        sb.AppendLine();
        sb.AppendLine(GeneratedCodeMetadata.GeneratedCodeAttribute);
        sb.AppendLine("internal static class PalORM_RegistryInitializer");
        sb.AppendLine("{");
        sb.AppendLine("    [global::System.Runtime.CompilerServices.ModuleInitializer]");
        sb.AppendLine("    internal static void Initialize()");
        sb.AppendLine("    {");
        sb.AppendLine("        var draft = new RegistryDraft();");
        List<TableModel[]> chunks = SplitIntoChunks(all);
        for (int index = 0; index < chunks.Count; index++)
            sb.AppendLine($"        AddChunk{index}(draft);");
        sb.AppendLine("        Register(draft);");
        sb.AppendLine("    }");
        sb.AppendLine();

        for (int index = 0; index < chunks.Count; index++)
        {
            TableModel[] chunk = chunks[index];
            int estimated = chunk.Sum(EstimateIl);
            sb.AppendLine($"    /// <summary>注册 {chunk.Length} 个实体（估算 IL ≈{estimated} B）——"
                + "分块边界即单方法 IL 的上界。</summary>");
            sb.AppendLine($"    private static void AddChunk{index}(RegistryDraft draft)");
            sb.AppendLine("    {");
            foreach (var model in chunk)
                AppendEntityPayload(sb, model);
            sb.AppendLine("    }");
            sb.AppendLine();
        }

        AppendRegisterMethod(sb);
        AppendDraftType(sb);
        sb.AppendLine("}");
        return sb.ToString();
    }

    /// <summary>按估算 IL 贪心切块——顺序保持模型原序，故各字典的插入顺序与切块前一致。</summary>
    private static List<TableModel[]> SplitIntoChunks(TableModel[] models)
    {
        var chunks = new List<TableModel[]>();
        var current = new List<TableModel>();
        int estimate = 0;
        foreach (var model in models)
        {
            int cost = EstimateIl(model);
            // 单实体就超预算时独占一块（current.Count 守卫）——切成空块没有意义
            if (current.Count > 0 && estimate + cost > ChunkIlBudget)
            {
                chunks.Add([.. current]);
                current.Clear();
                estimate = 0;
            }
            current.Add(model);
            estimate += cost;
        }
        if (current.Count > 0) chunks.Add([.. current]);
        return chunks;
    }

    private static int EstimateIl(TableModel model)
        => PerEntityIlEstimate + (PerColumnIlEstimate * model.Columns.AsSpan().Length);

    /// <summary>单个实体的全部注册项——15 个字典各一行到数行，顺序与字典顺序一致。
    /// 分块方法只调用它多次，因此实体级新增载荷（如新的可选字典）只需改这一处。</summary>
    private static void AppendEntityPayload(StringBuilder sb, TableModel m)
    {
        sb.AppendLine($"        draft.RowFactories[typeof({m.EntityTypeName})] = RowFactory_{m.GeneratedTypeSuffix}.Read;");
        sb.AppendLine($"        draft.TableNames[typeof({m.EntityTypeName})] = {MigrationEmitter.ToCSharpLiteral(m.TableName)};");

        sb.AppendLine($"        draft.CommandSqlsByDialect[typeof({m.EntityTypeName})] = new global::PalORM.CommandSqlByDialect(");
        AppendCommandSqlSet(sb, m, SqlGenerationDialect.Sqlite, indent: 12);
        AppendCommandSqlSet(sb, m, SqlGenerationDialect.PostgreSql, indent: 12);
        AppendCommandSqlSet(sb, m, SqlGenerationDialect.MySql, indent: 12, isLast: true);
        sb.AppendLine("        );");

        sb.AppendLine($"        draft.BindInsert[typeof({m.EntityTypeName})] = (cmd, obj, off) => CommandFactory_{m.GeneratedTypeSuffix}.BindInsertToBatch(cmd, ({m.EntityTypeName})obj, off);");
        sb.AppendLine($"        draft.BindUpdate[typeof({m.EntityTypeName})] = (cmd, obj) => CommandFactory_{m.GeneratedTypeSuffix}.BindUpdate(cmd, ({m.EntityTypeName})obj);");
        sb.AppendLine($"        draft.BindDelete[typeof({m.EntityTypeName})] = (cmd, key) => CommandFactory_{m.GeneratedTypeSuffix}.BindDelete(cmd, key);");

        // CrudMetadata 用聚合 ctor（CrudBindings + CrudColumns）避免 9 参参数列表（S107）。
        // 评审 2026-09-02：用不含 legacy SQL 载荷的新 ctor——方言 SQL 走 CommandSqlsByDialect。
        sb.AppendLine($"        draft.CrudMetadatas[typeof({m.EntityTypeName})] = new global::PalORM.CrudMetadata(");
        sb.AppendLine("                new global::PalORM.CrudBindings(");
        sb.AppendLine($"                    (cmd, obj, off) => CommandFactory_{m.GeneratedTypeSuffix}.BindInsertToBatch(cmd, ({m.EntityTypeName})obj, off),");
        sb.AppendLine($"                    (parameters, obj, off) => CommandFactory_{m.GeneratedTypeSuffix}.BindInsertValues(parameters, ({m.EntityTypeName})obj, off),");
        sb.AppendLine($"                    (cmd, obj) => CommandFactory_{m.GeneratedTypeSuffix}.BindUpsert(cmd, ({m.EntityTypeName})obj),");
        sb.AppendLine($"                    (cmd, obj) => CommandFactory_{m.GeneratedTypeSuffix}.BindUpdate(cmd, ({m.EntityTypeName})obj),");
        sb.AppendLine($"                    RowFactory_{m.GeneratedTypeSuffix}.Read,");
        // v5.6：批量 UPDATE 参数池的取值绑定器（只写 Value，不建参数）。放在末位可选参数，
        // 与 BindInsertValues 同机制；消费点 ExecuteBatchUpdateAsync 在 null 时回退逐行 BindUpdate。
        sb.AppendLine($"                    (parameters, obj, off) => CommandFactory_{m.GeneratedTypeSuffix}.BindUpdateValues(parameters, ({m.EntityTypeName})obj, off)),");
        // ITM-640：单次物化 Columns（本块原 3 处 AsSpan().ToArray() 重复分配；另 3 处
        // 分属独立 per-model 循环无法共用——复检轮计数订正）
        var columns = m.Columns.AsSpan().ToArray();
        string insertColumns = BuildStringArrayLiteral(
            columns.Where(static column => column.IsInsertable)
                .Select(static column => column.ColumnName));
        string upsertColumns = BuildStringArrayLiteral(
            columns.Where(static column => column.IsUpsertable)
                .Select(static column => column.ColumnName));
        // ITM-642：UpdateColumns 与 BuildUpdateSql/BindUpdate 同源同序（ITM-552 单一谓词）——
        // 运行时 BulkUpdateBatchAsync 消费本真源，不再解析生成 SQL 文本反解列名。
        string updateColumns = BuildStringArrayLiteral(
            columns.Where(CommandFactoryEmitter.IsUpdatableColumn)
                .Select(static column => column.ColumnName));
        sb.AppendLine("                new global::PalORM.CrudColumns(");
        sb.AppendLine($"                    {insertColumns},");
        sb.AppendLine($"                    {upsertColumns},");
        sb.AppendLine($"                    {updateColumns}),");
        bool hasConcurrency = columns.Any(c => c.IsConcurrencyToken);
        sb.AppendLine(hasConcurrency
            ? $"                obj => CommandFactory_{m.GeneratedTypeSuffix}.IncrementVersion(({m.EntityTypeName})obj),"
            : "                null,");
        sb.AppendLine($"                obj => CommandFactory_{m.GeneratedTypeSuffix}.HasDefaultKey(({m.EntityTypeName})obj));");

        // 按位组合 SoftDelete/TenantAware 特性；两者皆无则 None。
        var parts = new List<string>(2);
        if (m.IsSoftDelete) parts.Add("global::PalORM.EntityFeatures.SoftDelete");
        if (m.IsTenantAware) parts.Add("global::PalORM.EntityFeatures.TenantAware");
        string features = parts.Count == 0
            ? "global::PalORM.EntityFeatures.None"
            : string.Join(" | ", parts);
        sb.AppendLine($"        draft.EntityFeatures[typeof({m.EntityTypeName})] = {features};");

        // ITM-581: CanGenerateEntity 契约保证恰一个 [Key]——此处缺 PK 是上游破坏，
        // 静默兜底 "id" 会让错误列名进注册表，改为立即失败暴露契约破坏点。
        // ITM-640 处置 + 评审 2026-09-02：保留立即失败——transform 失败面已由 PALORM045
        // 兜底诊断覆盖（CanGenerateEntity 失败的实体到不了这里）；到达此处仅当管道自身回归，
        // 属不可达内部不变量断言而非用户错误面。
        var pk = columns.FirstOrDefault(c => c.IsPrimaryKey);
        string pkName = pk?.ColumnName ?? throw new InvalidOperationException(
            $"Entity '{m.EntityTypeName}' reached RegistryEmitter without a primary key column; " +
            "CanGenerateEntity should have rejected it.");
        sb.AppendLine($"        draft.PkColumns[typeof({m.EntityTypeName})] = {MigrationEmitter.ToCSharpLiteral(pkName)};");

        string names = BuildStringArrayLiteral(columns.Select(static column => column.ColumnName));
        sb.AppendLine($"        draft.ColumnNames[typeof({m.EntityTypeName})] = {names};");

        sb.AppendLine($"        draft.PropertyToColumn[typeof({m.EntityTypeName})] = new global::System.Collections.Generic.Dictionary<string, string>");
        sb.AppendLine("        {");
        foreach (var column in columns)
            sb.AppendLine($"            [{MigrationEmitter.ToCSharpLiteral(column.PropertyName)}] = {MigrationEmitter.ToCSharpLiteral(column.ColumnName)},");
        sb.AppendLine("        };");

        // 评审 2026-09-02 第二批（ADR-J）：legacy CreateTableSql 字典不再发射——其产物为
        // SQLite 风格单方言 DDL，运行时自 ITM-569 起拒绝执行；方言 DDL
        // （CreateTableSqlByDialect）是唯一真源。RegistryFragment.CreateTableSql 保留为
        // 空集默认的可选属性，仅兼容旧生成器片段。
        sb.AppendLine($"        draft.CreateTableSqlByDialect[typeof({m.EntityTypeName})] = new global::PalORM.CreateTableSqlSet(");
        sb.AppendLine($"                Migration_{m.GeneratedTypeSuffix}.CreateTableSqlite,");
        sb.AppendLine($"                Migration_{m.GeneratedTypeSuffix}.CreateTablePostgreSql,");
        sb.AppendLine($"                Migration_{m.GeneratedTypeSuffix}.CreateTableMySql);");

        // r18/ITM-672：零索引实体也发射空 CreateIndexSqlSet——运行时"缺键即拒绝"才能区分
        // "无索引"（空集，合法）与"旧生成器/手工片段"（键缺失，必须拒绝）。
        sb.AppendLine($"        draft.CreateIndexSqlByDialect[typeof({m.EntityTypeName})] = new global::PalORM.CreateIndexSqlSet(");
        sb.AppendLine($"                Migration_{m.GeneratedTypeSuffix}.CreateIndexesSqlite,");
        sb.AppendLine($"                Migration_{m.GeneratedTypeSuffix}.CreateIndexesPostgreSql,");
        sb.AppendLine($"                Migration_{m.GeneratedTypeSuffix}.CreateIndexesMySql);");

        bool hasGeneratedKey = columns.Any(static column => column.IsPrimaryKey && column.IsAutoIncrement);
        if (hasGeneratedKey)
            sb.AppendLine($"        draft.SetIdDelegates[typeof({m.EntityTypeName})] = (entity, id) => CommandFactory_{m.GeneratedTypeSuffix}.SetId(({m.EntityTypeName})entity, id);");

        // ITM-763(r21)：[SensitiveData] 掩码表——运行时载体。仅当存在敏感列时发射条目；
        // 无敏感列的片段缺省该属性（可选键，旧片段兼容）。消费链：QueryBuilder.Set 查表
        // → 记录参数名→掩码 → QueryContext.SensitiveParameterMasks → AuditInterceptor。
        if (columns.Any(static c => c.SensitiveMask is not null))
        {
            sb.AppendLine($"        draft.SensitiveColumnMasks[typeof({m.EntityTypeName})] = new global::System.Collections.Generic.Dictionary<string, string>");
            sb.AppendLine("        {");
            foreach (var column in columns)
                if (column.SensitiveMask is not null)
                    sb.AppendLine($"            [{MigrationEmitter.ToCSharpLiteral(column.ColumnName)}] = {MigrationEmitter.ToCSharpLiteral(column.SensitiveMask)},");
            sb.AppendLine("        };");
        }

        sb.AppendLine();
    }

    /// <summary>一次 <c>Register</c>：draft 的 15 个字典原样交给片段（运行时内部自行冻结，
    /// 不持有 draft 引用），因此分块不会带来重复拷贝。</summary>
    private static void AppendRegisterMethod(StringBuilder sb)
    {
        sb.AppendLine("    private static void Register(RegistryDraft draft)");
        sb.AppendLine("    {");
        sb.AppendLine("        global::PalORM.PalORM_Runtime.Register(new global::PalORM.RegistryFragment");
        sb.AppendLine("        {");
        sb.AppendLine("            RowFactories = draft.RowFactories,");
        sb.AppendLine("            TableNames = draft.TableNames,");
        sb.AppendLine("            CommandSqlsByDialect = draft.CommandSqlsByDialect,");
        sb.AppendLine("            BindInsert = draft.BindInsert,");
        sb.AppendLine("            BindUpdate = draft.BindUpdate,");
        sb.AppendLine("            BindDelete = draft.BindDelete,");
        sb.AppendLine("            CrudMetadatas = draft.CrudMetadatas,");
        sb.AppendLine("            EntityFeatures = draft.EntityFeatures,");
        sb.AppendLine("            PkColumns = draft.PkColumns,");
        sb.AppendLine("            ColumnNames = draft.ColumnNames,");
        sb.AppendLine("            PropertyToColumn = draft.PropertyToColumn,");
        sb.AppendLine("            CreateTableSqlByDialect = draft.CreateTableSqlByDialect,");
        sb.AppendLine("            CreateIndexSqlByDialect = draft.CreateIndexSqlByDialect,");
        sb.AppendLine("            SetIdDelegates = draft.SetIdDelegates,");
        sb.AppendLine("            SensitiveColumnMasks = draft.SensitiveColumnMasks,");
        sb.AppendLine("        });");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    /// <summary>分块写入用的可变载体——生成器私有类型，不进公共 API。
    /// 字段类型即 <c>RegistryFragment</c> 所需接口的实现类型，注册时直接传递引用。</summary>
    private static void AppendDraftType(StringBuilder sb)
    {
        sb.AppendLine("    /// <summary>分块构建期的可变载体（生成器私有）——最后整体交给 RegistryFragment。</summary>");
        sb.AppendLine("    private sealed class RegistryDraft");
        sb.AppendLine("    {");
        sb.AppendLine("        internal readonly global::System.Collections.Generic.Dictionary<global::System.Type, object> RowFactories = new();");
        sb.AppendLine("        internal readonly global::System.Collections.Generic.Dictionary<global::System.Type, string> TableNames = new();");
        sb.AppendLine("        internal readonly global::System.Collections.Generic.Dictionary<global::System.Type, global::PalORM.CommandSqlByDialect> CommandSqlsByDialect = new();");
        sb.AppendLine("        internal readonly global::System.Collections.Generic.Dictionary<global::System.Type, global::System.Action<global::System.Data.Common.DbCommand, object, int>> BindInsert = new();");
        sb.AppendLine("        internal readonly global::System.Collections.Generic.Dictionary<global::System.Type, global::System.Action<global::System.Data.Common.DbCommand, object>> BindUpdate = new();");
        sb.AppendLine("        internal readonly global::System.Collections.Generic.Dictionary<global::System.Type, global::System.Action<global::System.Data.Common.DbCommand, object>> BindDelete = new();");
        sb.AppendLine("        internal readonly global::System.Collections.Generic.Dictionary<global::System.Type, global::PalORM.CrudMetadata> CrudMetadatas = new();");
        sb.AppendLine("        internal readonly global::System.Collections.Generic.Dictionary<global::System.Type, global::PalORM.EntityFeatures> EntityFeatures = new();");
        sb.AppendLine("        internal readonly global::System.Collections.Generic.Dictionary<global::System.Type, string> PkColumns = new();");
        sb.AppendLine("        internal readonly global::System.Collections.Generic.Dictionary<global::System.Type, string[]> ColumnNames = new();");
        sb.AppendLine("        internal readonly global::System.Collections.Generic.Dictionary<global::System.Type, global::System.Collections.Generic.IReadOnlyDictionary<string, string>> PropertyToColumn = new();");
        sb.AppendLine("        internal readonly global::System.Collections.Generic.Dictionary<global::System.Type, global::PalORM.CreateTableSqlSet> CreateTableSqlByDialect = new();");
        sb.AppendLine("        internal readonly global::System.Collections.Generic.Dictionary<global::System.Type, global::PalORM.CreateIndexSqlSet> CreateIndexSqlByDialect = new();");
        sb.AppendLine("        internal readonly global::System.Collections.Generic.Dictionary<global::System.Type, global::System.Action<object, long>> SetIdDelegates = new();");
        sb.AppendLine("        internal readonly global::System.Collections.Generic.Dictionary<global::System.Type, global::System.Collections.Generic.IReadOnlyDictionary<string, string>> SensitiveColumnMasks = new();");
        sb.AppendLine("    }");
    }

    private static void AppendCommandSqlSet(
        StringBuilder builder,
        TableModel model,
        SqlGenerationDialect dialect,
        int indent,
        bool isLast = false)
    {
        string pad = new(' ', indent);
        string insert = CommandFactoryEmitter.BuildInsertSql(model, dialect);
        string update = CommandFactoryEmitter.BuildUpdateSql(model, dialect);
        string delete = CommandFactoryEmitter.BuildDeleteSql(model, dialect);
        string returning = CommandFactoryEmitter.BuildInsertReturningSql(model, dialect);
        string upsertReturning = CommandFactoryEmitter.BuildUpsertReturningSql(model, dialect);
        string upsertMySql = CommandFactoryEmitter.BuildUpsertMySqlSql(model, dialect);
        string insertLastId = CommandFactoryEmitter.BuildInsertWithLastInsertIdSql(model, dialect);
        builder.AppendLine($"{pad}new global::PalORM.CommandSqlSet(");
        builder.AppendLine($"{pad}    {MigrationEmitter.ToCSharpLiteral(insert)},");
        builder.AppendLine($"{pad}    {MigrationEmitter.ToCSharpLiteral(update)},");
        builder.AppendLine($"{pad}    {MigrationEmitter.ToCSharpLiteral(delete)},");
        builder.AppendLine($"{pad}    {MigrationEmitter.ToCSharpLiteral(returning)},");
        builder.AppendLine($"{pad}    {MigrationEmitter.ToCSharpLiteral(upsertReturning)},");
        builder.AppendLine($"{pad}    {MigrationEmitter.ToCSharpLiteral(upsertMySql)},");
        builder.AppendLine($"{pad}    {MigrationEmitter.ToCSharpLiteral(insertLastId)}){(isLast ? "" : ",")}");
    }

    private static string BuildStringArrayLiteral(IEnumerable<string> values)
    {
        string[] items = values.ToArray();
        if (items.Length == 0)
            return "global::System.Array.Empty<string>()";

        return "new[] { " + string.Join(", ",
            items.Select(MigrationEmitter.ToCSharpLiteral)) + " }";
    }
}
