using System.Text;

namespace PalORM.SourceGen;

/// <summary>RowFactory 代码生成器——为每个 [Table] 类生成 IRowFactory&lt;T&gt;.Read() 实现。</summary>
internal static class RowFactoryEmitter
{
    internal static string Generate(TableModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace PalORM.Generated;");
        sb.AppendLine();
        sb.AppendLine($"internal sealed class RowFactory_{model.GeneratedTypeSuffix} : global::PalORM.IRowFactory<{model.EntityTypeName}>");
        sb.AppendLine("{");
        sb.AppendLine($"    internal static readonly RowFactory_{model.GeneratedTypeSuffix} Instance = new();");
        sb.AppendLine($"    private RowFactory_{model.GeneratedTypeSuffix}() {{ }}");
        sb.AppendLine();
        sb.AppendLine($"    public {model.EntityTypeName} Read(global::System.Data.Common.DbDataReader r)");
        sb.AppendLine("    {");
        sb.AppendLine($"        return new {model.EntityTypeName}");
        sb.AppendLine("        {");

        int ordinal = 0;
        foreach (var col in model.Columns)
        {
            string readCall = GetReadExpression(col, ordinal, model.GeneratedTypeSuffix);
            sb.AppendLine($"            {col.PropertyName} = {readCall},");
            ordinal++;
        }

        sb.AppendLine("        };");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string GetReadExpression(ColumnModel col, int ordinal, string generatedTypeSuffix)
    {
        // 可空类型处理
        if (col.IsNullable)
        {
            string nonNullRead = GetNonNullReadExpression(col, ordinal, generatedTypeSuffix);
            return $"r.IsDBNull({ordinal}) ? null : {nonNullRead}";
        }

        return GetNonNullReadExpression(col, ordinal, generatedTypeSuffix);
    }

    private static string GetNonNullReadExpression(ColumnModel col, int ordinal, string generatedTypeSuffix)
    {
        // Converter 的 provider 类型在编译期确定，读取后再转换为实体属性类型。
        if (col.ConverterTypeName is not null)
        {
            string providerRead = GetRawReadExpression(
                col.ProviderClrTypeName,
                ordinal,
                generatedTypeSuffix);
            return $"((global::PalORM.IValueConverter<{col.ClrTypeName}, {col.ProviderClrTypeName}>)new {col.ConverterTypeName}()).FromProvider({providerRead})";
        }

        // 字符串 OwnedJson 是原始 JSON；对象 OwnedJson 仅走源生成 JsonTypeInfo<T>。
        if (col.IsOwnedJson && col.ClrTypeName is not "string" and not "global::System.String")
            return $"global::System.Text.Json.JsonSerializer.Deserialize(r.GetString({ordinal}), CommandFactory_{generatedTypeSuffix}.JsonTypeInfo_{col.PropertyName})!";

        return GetRawReadExpression(
            col.ProviderClrTypeName,
            ordinal,
            generatedTypeSuffix);
    }

    private static string GetRawReadExpression(
        string clrTypeName,
        int ordinal,
        string generatedTypeSuffix)
    {
        string tn = clrTypeName;
        if (tn.StartsWith("global::", StringComparison.Ordinal))
            tn = tn.Substring("global::".Length);

        return tn switch
        {
            "long" or "System.Int64" => $"r.GetInt64({ordinal})",
            "int" or "System.Int32" => $"r.GetInt32({ordinal})",
            "string" or "System.String" => $"r.GetString({ordinal})",
            "bool" or "System.Boolean" => $"r.GetBoolean({ordinal})",
            "decimal" or "System.Decimal" => $"r.GetDecimal({ordinal})",
            "double" or "System.Double" => $"r.GetDouble({ordinal})",
            "float" or "System.Single" => $"r.GetFloat({ordinal})",
            "System.Guid" => $"r.GetGuid({ordinal})",
            "System.DateTime" => $"r.GetDateTime({ordinal})",
            "System.DateTimeOffset"
                => $"TypeMapper_{generatedTypeSuffix}.ReadDateTimeOffset(r, {ordinal})",
            "System.DateOnly" => $"global::System.DateOnly.FromDateTime(r.GetDateTime({ordinal}))",
            "System.TimeOnly" => $"global::System.TimeOnly.FromTimeSpan(r.GetTimeSpan({ordinal}))",
            "System.TimeSpan" => $"r.GetTimeSpan({ordinal})",
            "short" or "System.Int16" => $"r.GetInt16({ordinal})",
            "byte" or "System.Byte" => $"r.GetByte({ordinal})",
            "char" or "System.Char" => $"r.GetChar({ordinal})",
            "byte[]" or "System.Byte[]" => $"(byte[])r.GetValue({ordinal})",
            _ => $"({clrTypeName})r.GetValue({ordinal})"
        };
    }
}
