using System.Text;
using Microsoft.CodeAnalysis.CSharp;

namespace PalORM.SourceGen;

/// <summary>RowFactory 代码生成器——为每个 [Table] 类生成静态 Func&lt;DbDataReader, T&gt; Read 委托。
/// <para><b>v3.1 性能优化 1</b>: emit 从 <c>sealed class : IRowFactory&lt;T&gt;</c> 迁移到
/// <c>static class + static readonly Func&lt;DbDataReader, T&gt; Read</c>，调用方直接委托 invoke，
/// 消除接口虚分发（JIT 无法跨接口边界内联）。.NET 8+ JIT 对 static delegate invoke 有更好内联支持。</para></summary>
internal static class RowFactoryEmitter
{
    internal static string Generate(TableModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace PalORM.Generated;");
        sb.AppendLine();
        sb.AppendLine(GeneratedCodeMetadata.GeneratedCodeAttribute);
        sb.AppendLine($"internal static class RowFactory_{model.GeneratedTypeSuffix}");
        sb.AppendLine("{");

        // v3.1 性能优化 2：Converter 单例缓存——为每个 [Converter] 列生成 static readonly 字段。
        // 替代旧 emit 中每次 Read 都 `new Converter()` 的分配。converter 是 stateless 类型，
        // 重复 new 是无意义的 GC Gen0 压力（带 Converter 的实体每行每列省一次分配）。
        // 字段必须声明在 Read 之前：Read 是 static lambda 引用这些字段，编译器要求
        // 字段已初始化——声明顺序保证 Read 在首次调用前字段已完成静态初始化。
        int converterCount = 0;
        foreach (var col in model.Columns)
        {
            if (col.ConverterTypeName is null) continue;
            sb.AppendLine($"    private static readonly global::PalORM.IValueConverter<{col.ClrTypeName}, {col.ProviderClrTypeName}> _conv_{col.PropertyName} = new {col.ConverterTypeName}();");
            converterCount++;
        }
        if (converterCount > 0)
            sb.AppendLine();

        // v3.1 性能优化 1：Read 委托——static readonly，由 JIT 特化为直接调用（消除接口虚分发）。
        // static lambda 保证无闭包捕获，JIT 生成代码与直接方法调用等价。
        sb.AppendLine($"    internal static readonly global::System.Func<global::System.Data.Common.DbDataReader, {model.EntityTypeName}> Read");
        sb.AppendLine($"        = static (global::System.Data.Common.DbDataReader r) =>");
        sb.AppendLine("    {");
        sb.AppendLine($"        return new {model.EntityTypeName}");
        sb.AppendLine("        {");

        int ordinal = 0;
        foreach (var col in model.Columns)
        {
            string readCall = GetReadExpression(col, ordinal, model.GeneratedTypeSuffix);
            sb.AppendLine($"            {col.EscapedPropertyName} = {readCall},");
            ordinal++;
        }

        sb.AppendLine("        };");
        sb.AppendLine("    };");

        // ITM-520：char 列经 GetString(o)[0] 读取，空串会抛 IndexOutOfRange 且无列名可诊断。
        // 统一走辅助方法，空串时抛带列名的 InvalidOperationException。仅在存在 char 列时生成。
        if (HasCharColumn(model))
        {
            sb.AppendLine();
            sb.AppendLine("    private static char ReadChar(global::System.Data.Common.DbDataReader r, int ordinal, string column)");
            sb.AppendLine("    {");
            sb.AppendLine("        string s = r.GetString(ordinal);");
            sb.AppendLine("        if (s.Length == 0)");
            sb.AppendLine("            throw new global::System.InvalidOperationException(");
            sb.AppendLine("                $\"Column '{column}' maps to char but contained an empty string.\");");
            sb.AppendLine("        return s[0];");
            sb.AppendLine("    }");
        }
        // ITM-553（v6.1）：字符串存储枚举的解析辅助——生成式 switch（成员名→常量，
        // AOT 零反射），未定义值抛带原始值的 InvalidOperationException（防静默默认值错数据）。
        foreach (var col in model.Columns)
        {
            if (col.EnumStorage != EnumStorageKind.AsString || col.EnumParseSwitchBody is null) continue;
            sb.AppendLine();
            sb.AppendLine($"    private static {col.EnumClrTypeName} Parse_{col.PropertyName}(string value)");
            sb.AppendLine("    {");
            sb.AppendLine("        return value switch");
            sb.AppendLine("        {");
            sb.Append("            ").AppendLine(col.EnumParseSwitchBody);
            sb.AppendLine("            _ => throw new global::System.InvalidOperationException(\"Value '\" + value + \"' does not match a defined member of " + col.EnumClrTypeName + ".\")");
            sb.AppendLine("        };");
            sb.AppendLine("    }");
        }
        sb.AppendLine("}");
        return sb.ToString();
    }

    /// <summary>模型是否含 char 列——决定是否生成 ReadChar 辅助方法（ITM-520）。</summary>
    private static bool HasCharColumn(TableModel model)
    {
        foreach (var col in model.Columns)
        {
            string tn = col.ProviderClrTypeName;
            // ITM-550：与 GetRawReadExpression 的读表达式 switch 对称——该 switch 剥掉 global:: 前缀后
            // 对 "char"/"System.Char" 都产 ReadChar。此处补 "System.Char"：若 ProviderClrTypeName 出现
            // 裸 "System.Char"（如 converter 的 provider 类型），避免 HasCharColumn 漏判导致 ReadChar 不生成 → CS0103。
            if (tn is "char" or "global::System.Char" or "System.Char") return true;
        }
        return false;
    }

    private static string GetReadExpression(ColumnModel col, int ordinal, string generatedTypeSuffix)
    {
        // GEN-007（2026-09-23）：可空性判定分三态，不再只认 NRT 注解。
        //   ① Annotated（`string?`）→ IsNullable：DB NULL 物化为 null（既有行为）。
        //   ② None（`#nullable disable` 的引用类型）→ IsNullabilityUnknown：可空性无从判断，
        //      此前直读会让 DB NULL 落到驱动层 SqlNullValueException（无列名无实体名）。
        //      现改为命名化响亮失败：消息带列名与属性名，指向"启用 NRT 标注可空或让列 NOT NULL"。
        //      不向非空属性注入 null——那会违反实体契约并把失败推给下游 NRE（防静默错误优先）。
        //   ③ NotAnnotated（NRT 开启且声明非空）→ 直读：非空是显式契约，不加每行 IsDBNull 开销
        //      （可空列双读的代价见 L44 登记，不扩大到非空列）。
        // 可空类型处理
        if (col.IsNullable)
        {
            string nonNullRead = GetNonNullReadExpression(col, ordinal, generatedTypeSuffix);
            return $"r.IsDBNull({ordinal}) ? null : {nonNullRead}";
        }

        if (col.IsNullabilityUnknown)
        {
            string nonNullRead = GetNonNullReadExpression(col, ordinal, generatedTypeSuffix);
            // ITM-831（r22 登记，r23 实修）：消息整段经 FormatLiteral 转义再进生成代码的
            // 字符串字面量——与同文件 char 路径同口径。裸拼列名/属性名时，含 " 或 \ 的
            // 标识符会让生成物报 CS1010/CS1009 语法错误（报错点落在生成物内难归因）。
            string message = SymbolDisplay.FormatLiteral(
                $"Column '{col.ColumnName}' (property '{col.PropertyName}') returned NULL, but the "
                + "nullability of the property is unknown: enable nullable reference types on the entity "
                + "and mark it nullable, or make the column NOT NULL.",
                quote: true);
            return $"r.IsDBNull({ordinal}) ? throw new global::System.InvalidOperationException("
                + $"{message}) : {nonNullRead}";
        }

        return GetNonNullReadExpression(col, ordinal, generatedTypeSuffix);
    }

    private static string GetNonNullReadExpression(ColumnModel col, int ordinal, string generatedTypeSuffix)
    {
        // Converter 的 provider 类型在编译期确定，读取后再转换为实体属性类型。
        // v3.1：引用类级 static readonly 字段 _conv_<prop>，避免每次 Read 分配新 Converter。
        // 抚慰符 ! 告知 NRT 分析器：static readonly 字段已完成初始化（字段声明在 Read 之前，
        // 静态构造函数完成前 Read 不会被调用），lambda 体内引用非空。
        if (col.ConverterTypeName is not null)
        {
            string providerRead = GetRawReadExpression(
                col.ProviderClrTypeName,
                ordinal,
                col.ColumnName);
            return $"_conv_{col.PropertyName}!.FromProvider({providerRead})";
        }

        // ITM-553（v6.1）：枚举列读路径——provider 类型已覆写（string/int/long），原始读取后
        // 强转回枚举（int→E / long→E 显式合法）；字符串形态经生成式 switch 解析（AOT 零反射，
        // 未定义成员响亮失败而非返回默认值）。枚举恒无 converter（×[Converter] 由 PALORM053 拦截）。
        if (col.EnumStorage != EnumStorageKind.None)
        {
            string raw = GetRawReadExpression(col.ProviderClrTypeName, ordinal, col.ColumnName);
            return col.EnumStorage == EnumStorageKind.AsString
                ? $"Parse_{col.PropertyName}({raw})"
                : $"({col.EnumClrTypeName}){raw}";
        }

        // 字符串 OwnedJson 是原始 JSON；对象 OwnedJson 仅走源生成 JsonTypeInfo<T>。
        // L45（2026-09-25 Span 化）经 2026-09-26 发布验证**实测证伪回滚**：GetFieldValue<byte[]>
        // 对 TEXT 列的 UTF-8 语义仅在 Microsoft.Data.Sqlite 成立（探针实测）；MySqlConnector 对
        // TEXT 列 GetFieldValue<byte[]> 抛 InvalidCastException（CI MySQL Native AOT job 实证，
        // 发布 run 36223824623）。RowFactory 是方言无关生成物（TableModel 无方言维度，
        // 一套生成物服务三方言是根基架构），无法方言条件 emit；且收益面窄（OwnedJson 列读
        // 分配的局部优化）远不抵一次 INT cast 故障的定位成本。维持 GetString 通用形态。
        if (col.IsOwnedJson && col.ClrTypeName is not "string" and not "global::System.String")
            return $"global::System.Text.Json.JsonSerializer.Deserialize(r.GetString({ordinal}), CommandFactory_{generatedTypeSuffix}.JsonTypeInfo_{col.PropertyName})!";

        return GetRawReadExpression(
            col.ProviderClrTypeName,
            ordinal,
            col.ColumnName);
    }

    private static string GetRawReadExpression(
        string clrTypeName,
        int ordinal,
        string columnName)
    {
        string tn = clrTypeName;
        if (tn.StartsWith("global::", StringComparison.Ordinal))
            tn = tn.Substring("global::".Length);

        return tn switch
        {
            "long" or "System.Int64" => $"r.GetInt64({ordinal})",
            "int" or "System.Int32" => $"r.GetInt32({ordinal})",
            "string" or "System.String" => $"r.GetString({ordinal})",
            "bool" or "System.Boolean" => $"r.GetBoolean({ordinal})",
            "decimal" or "System.Decimal" => $"r.GetDecimal({ordinal})",
            "double" or "System.Double" => $"r.GetDouble({ordinal})",
            "float" or "System.Single" => $"r.GetFloat({ordinal})",
            "System.Guid" => $"r.GetGuid({ordinal})",
            "System.DateTime" => $"r.GetDateTime({ordinal})",
            "System.DateTimeOffset"
                => $"r.GetFieldValue<global::System.DateTimeOffset>({ordinal})",
            "System.DateOnly" => $"global::System.DateOnly.FromDateTime(r.GetDateTime({ordinal}))",
            // DbDataReader 无 GetTimeSpan 实例方法（仅部分驱动子类提供），必须走泛型 GetFieldValue
            "System.TimeOnly" => $"global::System.TimeOnly.FromTimeSpan(r.GetFieldValue<global::System.TimeSpan>({ordinal}))",
            "System.TimeSpan" => $"r.GetFieldValue<global::System.TimeSpan>({ordinal})",
            "short" or "System.Int16" => $"r.GetInt16({ordinal})",
            "byte" or "System.Byte" => $"r.GetByte({ordinal})",
            // ITM-814（r23 实修）：补齐窄整型无符号族与底层 long 的枚举——此前落
            // (T)r.GetValue(i) 装箱拆箱路径：驱动把数值列装箱为 Int64/Int32 时拆箱必抛
            // InvalidCastException（byte[] 之外的引用类型不走本 switch 的 provider 形态，
            // 不受影响）。枚举底层 long（: long）同样必须显式 GetFieldValue。
            "ushort" or "System.UInt16"
                => $"global::System.Convert.ToUInt16(r.GetFieldValue<global::System.UInt64>({ordinal}), global::System.Globalization.CultureInfo.InvariantCulture)",
            "uint" or "System.UInt32"
                => $"global::System.Convert.ToUInt32(r.GetFieldValue<global::System.UInt64>({ordinal}), global::System.Globalization.CultureInfo.InvariantCulture)",
            "sbyte" or "System.SByte"
                => $"global::System.Convert.ToSByte(r.GetFieldValue<global::System.Int64>({ordinal}), global::System.Globalization.CultureInfo.InvariantCulture)",
            "ulong" or "System.UInt64" => $"r.GetFieldValue<global::System.UInt64>({ordinal})",
            // ITM-520：Microsoft.Data.Sqlite/Npgsql 的 GetChar 抛 NotSupportedException，
            // 经字符串读取；空串守卫走 ReadChar，抛带列名异常而非裸 IndexOutOfRange
            "char" or "System.Char" => $"ReadChar(r, {ordinal}, {SymbolDisplay.FormatLiteral(columnName, quote: true)})",
            // v4.4：GetFieldValue<byte[]> 比 GetValue 反射路径更快，对齐 DateTimeOffset/TimeSpan 路径
            "byte[]" or "System.Byte[]" => $"r.GetFieldValue<byte[]>({ordinal})",
            _ => $"({clrTypeName})r.GetValue({ordinal})"
        };
    }
}
