using System.Text;
using Microsoft.CodeAnalysis.CSharp;

namespace PalORM.SourceGen;

/// <summary>RowFactory 代码生成器——为每个 [Table] 类生成 IRowFactory&lt;T&gt;.Read() 实现。</summary>
internal static class RowFactoryEmitter
{
    internal static string Generate(TableModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace PalORM.Generated;");
        sb.AppendLine();
        sb.AppendLine("[global::System.CodeDom.Compiler.GeneratedCode(\"PalORM.SourceGen\", \"2.0.0\")]");
        sb.AppendLine($"internal sealed class RowFactory_{model.GeneratedTypeSuffix} : global::PalORM.IRowFactory<{model.EntityTypeName}>");
        sb.AppendLine("{");
        sb.AppendLine($"    internal static readonly RowFactory_{model.GeneratedTypeSuffix} Instance = new();");
        sb.AppendLine($"    private RowFactory_{model.GeneratedTypeSuffix}() {{ }}");
        sb.AppendLine();
        sb.AppendLine($"    public {model.EntityTypeName} Read(global::System.Data.Common.DbDataReader r)");
        sb.AppendLine("    {");
        sb.AppendLine($"        return new {model.EntityTypeName}");
        sb.AppendLine("        {");

        int ordinal = 0;
        foreach (var col in model.Columns)
        {
            string readCall = GetReadExpression(col, ordinal, model.GeneratedTypeSuffix);
            sb.AppendLine($"            {col.PropertyName} = {readCall},");
            ordinal++;
        }

        sb.AppendLine("        };");
        sb.AppendLine("    }");

        // ITM-520：char 列经 GetString(o)[0] 读取，空串会抛 IndexOutOfRange 且无列名可诊断。
        // 统一走辅助方法，空串时抛带列名的 InvalidOperationException。仅在存在 char 列时生成。
        if (HasCharColumn(model))
        {
            sb.AppendLine();
            sb.AppendLine("    private static char ReadChar(global::System.Data.Common.DbDataReader r, int ordinal, string column)");
            sb.AppendLine("    {");
            sb.AppendLine("        string s = r.GetString(ordinal);");
            sb.AppendLine("        if (s.Length == 0)");
            sb.AppendLine("            throw new global::System.InvalidOperationException(");
            sb.AppendLine("                $\"Column '{column}' maps to char but contained an empty string.\");");
            sb.AppendLine("        return s[0];");
            sb.AppendLine("    }");
        }
        sb.AppendLine("}");
        return sb.ToString();
    }

    /// <summary>模型是否含 char 列——决定是否生成 ReadChar 辅助方法（ITM-520）。</summary>
    private static bool HasCharColumn(TableModel model)
    {
        foreach (var col in model.Columns)
        {
            string tn = col.ProviderClrTypeName;
            // ITM-550：与 GetRawReadExpression 的读表达式 switch 对称——该 switch 剥掉 global:: 前缀后
            // 对 "char"/"System.Char" 都产 ReadChar。此处补 "System.Char"：若 ProviderClrTypeName 出现
            // 裸 "System.Char"（如 converter 的 provider 类型），避免 HasCharColumn 漏判导致 ReadChar 不生成 → CS0103。
            if (tn is "char" or "global::System.Char" or "System.Char") return true;
        }
        return false;
    }

    private static string GetReadExpression(ColumnModel col, int ordinal, string generatedTypeSuffix)
    {
        // ITM-536 已知限制：可空判定依赖 NRT 注解（IsNullable ← NullableAnnotation.Annotated）。
        // 在 `#nullable disable` 上下文里，引用类型（string 等）无 Annotated 注解，会被当作非空、
        // 不生成 IsDBNull 守卫；若该列在 DB 里为 NULL，GetString 会抛 SqlNullValueException。
        // 规避方法：实体所在文件启用 `#nullable enable`，把真正可空的列显式标为 `string?`。
        // 此处不改可空推断逻辑——放宽会波及所有列的守卫生成，影响面过大。
        // 可空类型处理
        if (col.IsNullable)
        {
            string nonNullRead = GetNonNullReadExpression(col, ordinal, generatedTypeSuffix);
            return $"r.IsDBNull({ordinal}) ? null : {nonNullRead}";
        }

        return GetNonNullReadExpression(col, ordinal, generatedTypeSuffix);
    }

    private static string GetNonNullReadExpression(ColumnModel col, int ordinal, string generatedTypeSuffix)
    {
        // Converter 的 provider 类型在编译期确定，读取后再转换为实体属性类型。
        if (col.ConverterTypeName is not null)
        {
            string providerRead = GetRawReadExpression(
                col.ProviderClrTypeName,
                ordinal,
                generatedTypeSuffix,
                col.ColumnName);
            return $"((global::PalORM.IValueConverter<{col.ClrTypeName}, {col.ProviderClrTypeName}>)new {col.ConverterTypeName}()).FromProvider({providerRead})";
        }

        // 字符串 OwnedJson 是原始 JSON；对象 OwnedJson 仅走源生成 JsonTypeInfo<T>。
        if (col.IsOwnedJson && col.ClrTypeName is not "string" and not "global::System.String")
            return $"global::System.Text.Json.JsonSerializer.Deserialize(r.GetString({ordinal}), CommandFactory_{generatedTypeSuffix}.JsonTypeInfo_{col.PropertyName})!";

        return GetRawReadExpression(
            col.ProviderClrTypeName,
            ordinal,
            generatedTypeSuffix,
            col.ColumnName);
    }

    private static string GetRawReadExpression(
        string clrTypeName,
        int ordinal,
        string generatedTypeSuffix,
        string columnName)
    {
        string tn = clrTypeName;
        if (tn.StartsWith("global::", StringComparison.Ordinal))
            tn = tn.Substring("global::".Length);

        return tn switch
        {
            "long" or "System.Int64" => $"r.GetInt64({ordinal})",
            "int" or "System.Int32" => $"r.GetInt32({ordinal})",
            "string" or "System.String" => $"r.GetString({ordinal})",
            "bool" or "System.Boolean" => $"r.GetBoolean({ordinal})",
            "decimal" or "System.Decimal" => $"r.GetDecimal({ordinal})",
            "double" or "System.Double" => $"r.GetDouble({ordinal})",
            "float" or "System.Single" => $"r.GetFloat({ordinal})",
            "System.Guid" => $"r.GetGuid({ordinal})",
            "System.DateTime" => $"r.GetDateTime({ordinal})",
            "System.DateTimeOffset"
                => $"TypeMapper_{generatedTypeSuffix}.ReadDateTimeOffset(r, {ordinal})",
            "System.DateOnly" => $"global::System.DateOnly.FromDateTime(r.GetDateTime({ordinal}))",
            // DbDataReader 无 GetTimeSpan 实例方法（仅部分驱动子类提供），必须走泛型 GetFieldValue
            "System.TimeOnly" => $"global::System.TimeOnly.FromTimeSpan(r.GetFieldValue<global::System.TimeSpan>({ordinal}))",
            "System.TimeSpan" => $"r.GetFieldValue<global::System.TimeSpan>({ordinal})",
            "short" or "System.Int16" => $"r.GetInt16({ordinal})",
            "byte" or "System.Byte" => $"r.GetByte({ordinal})",
            // ITM-520：Microsoft.Data.Sqlite/Npgsql 的 GetChar 抛 NotSupportedException，
            // 经字符串读取；空串守卫走 ReadChar，抛带列名异常而非裸 IndexOutOfRange
            "char" or "System.Char" => $"ReadChar(r, {ordinal}, {SymbolDisplay.FormatLiteral(columnName, quote: true)})",
            "byte[]" or "System.Byte[]" => $"(byte[])r.GetValue({ordinal})",
            _ => $"({clrTypeName})r.GetValue({ordinal})"
        };
    }
}
