using System.Text;
using Microsoft.CodeAnalysis;

namespace PalORM.SourceGen;

/// <summary>[SqlTemplate("name")] 源生成器——为高频查询生成静态 FormattableString 常量。
/// 与 AsPrepared() 配合时，执行管线在参数绑定后调用 DbCommand.PrepareAsync。</summary>
internal static class SqlTemplateEmitter
{
    internal static string? Generate(GeneratorAttributeSyntaxContext ctx, CancellationToken ct)
    {
        if (ctx.TargetSymbol is not IMethodSymbol method)
            return null;

        var attr = method.GetAttributes().FirstOrDefault(a =>
            a.AttributeClass?.Name is "SqlTemplateAttribute" or "SqlTemplate"
            && a.AttributeClass?.ContainingNamespace?.ToDisplayString() is "PalORM");
        if (attr?.ConstructorArguments.Length != 1)
            return null;

        string templateName = attr.ConstructorArguments[0].Value?.ToString() ?? "";
        if (string.IsNullOrEmpty(templateName))
            return null;

        // 从方法体提取 SQL 文本
        string? methodBody = null;
        var syntaxRef = method.DeclaringSyntaxReferences.FirstOrDefault();
        if (syntaxRef is not null)
        {
            var syntax = syntaxRef.GetSyntax(ct);
            methodBody = syntax.ToString();
        }

        if (string.IsNullOrEmpty(methodBody))
            return null;

        // 提取 return 语句中的 FormattableString
        string? sql = ExtractFormattableString(methodBody!);
        if (sql is null) return null;

        string ns = method.ContainingNamespace?.IsGlobalNamespace == true
            ? "PalORM.Generated"
            : method.ContainingNamespace?.ToDisplayString() ?? "PalORM.Generated";

        string escaped = sql.Replace("\"", "\"\"");
        return $@"// <auto-generated/>
#nullable enable

namespace {ns};

/// <summary>编译期 SQL 模板——与 QueryBuilder.AsPrepared() 配合调用 DbCommand.PrepareAsync。</summary>
public static class SqlTemplates
{{
    /// <summary>模板: {templateName}</summary>
    public static readonly global::System.FormattableString {templateName} = $@""{escaped}"";
}}
";
    }

    private static string? ExtractFormattableString(string methodBody)
    {
        // 查找 $"..." 或 return $"..." 模式
        int dollar = methodBody.IndexOf("$\"", StringComparison.Ordinal);
        if (dollar < 0) return null;

        // 找到 $"..."; 或 $"...)"; 的结束位置
        int start = dollar + 2; // 跳过 $"
        int end = FindClosingQuote(methodBody, start);
        if (end < 0) return null;

        return methodBody.Substring(dollar + 1, end - dollar); // 包含 $"..."
    }

    private static int FindClosingQuote(string text, int start)
    {
        for (int i = start; i < text.Length - 1; i++)
        {
            if (text[i] == '"' && text[i + 1] != '"')
                return i;
            if (text[i] == '"' && text[i + 1] == '"')
                i++; // 跳过转义引号
        }
        return -1;
    }
}
