

using System.Text;

namespace PalORM.SourceGen;

/// <summary>TypeMapper 代码生成器——为自定义类型生成 DB↔CLR 转换方法。</summary>
internal static class TypeMapperEmitter
{
    internal static string Generate(TableModel model)
    {
        bool hasDateTimeOffset = model.Columns.AsSpan().ToArray().Any(static column =>
            column.ProviderClrTypeName.Contains("DateTimeOffset"));
        if (!hasDateTimeOffset)
            return string.Empty;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine($"namespace PalORM.Generated;");
        sb.AppendLine();
        sb.AppendLine("[global::System.CodeDom.Compiler.GeneratedCode(\"PalORM.SourceGen\", \"2.0.0\")]");
        sb.AppendLine($"internal static class TypeMapper_{model.GeneratedTypeSuffix}");
        sb.AppendLine("{");
        sb.AppendLine("    internal static global::System.DateTimeOffset ReadDateTimeOffset(global::System.Data.Common.DbDataReader r, int ord)");
        sb.AppendLine("        => r.GetFieldValue<global::System.DateTimeOffset>(ord);");
        sb.AppendLine("}");
        return sb.ToString();
    }
}
